bcgov/business-filings-ui

Jenkinsfile

*Issue #:* n/a
updated Jenkinsfile for new context dir

updated Jenkinsfile for new context dir

---

package-lock.json

updated package lock for common components 2.0.48

---

package-lock.json
package.json

bumped version to 2.6.1

---

package-lock.json
package.json

- reverted sbc-common-components dependency to 2.0.42
- also updated app name in package.json

reverted sbc-common-components dependency to 2.0.42

---

.dockerignore
.github/workflows/build-master.yml
.github/workflows/pr.yml
Dockerfile
nginx.conf

Add github Actions

---

src/components/Dashboard/FilingHistoryList.vue
src/views/Correction.vue

*Issue #:* /bcgov/entity#2607
- fixed AGM date for paper filings

fixed AGM date for paper filings

---

package-lock.json
package.json
public/config/configuration.json
public/config/local-configuration.json

*Issue #:* /bcgov/entity#2720
- updated sbc-common-components dependency to 2.0.50
- also updated BUSINESS_URL in configuration.json (same as current Dev config map)

updated sbc-common-components dependency to 2.0.50

---

package-lock.json
package.json

updated sbc-common-components dependency to 2.0.52

---

package-lock.json
package.json

updated sbc-common-components dependency to 2.0.53

---

src/components/Dashboard/FilingHistoryList.vue
src/components/common/DetailComment.vue
src/components/dialogs/AddCommentDialog.vue
src/views/Correction.vue

*Issue #:* /bcgov/entity#2757
Note: As of this PR the unit tests are still broken. I fixed them in a different task/branch.

changed detail comment labels

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/common/DetailComment.vue
src/components/dialogs/AddCommentDialog.vue
src/views/Correction.vue

*Issue #:* /bcgov/entity#2720 and /bcgov/entity#2757
- updated sbc-common-components dependency to 2.0.52
- updated sbc-common-components dependency to 2.0.53
- changed detail comment labels

Merge in changes from Release 2.6.0

---

tests/unit/Dashboard.spec.ts

*Issue #:* /bcgov/entity#2719
- "vm" was already declared in the upper scope so I just created a new describe section for the subject tests

fixed code smells

---

.sonarcloud.properties

I copied this file from lear repo and then updated it.

Updated .sonarcloud.properties file

---

src/components/Dashboard/FilingHistoryList.vue
src/components/common/Directors.vue
src/components/common/StaffPayment.vue
src/mixins/entityFilter-mixin.ts
src/mixins/resource-lookup-mixin.ts
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue

This is Part 2 of the the Correction Filing task, which includes:
- fixed a bug in Filing History List
- updated payment option behaviour per Scott
- updated Staff Payment in AR, COD and COA filings
- always show Staff Payment section for staff
- save/fetch new flags
- updated filing data logic to set flags per code
Part 3 will implement:
- resume a draft Correction filing
- updates to unit tests

correction filing (part 2)

---

public/config/configuration.json
public/config/local-configuration.json
src/main.ts

*Issue #:* /bcgov/entity#2790
- also updated Signin URL in local config files

removed Return URL from login redirect

---

src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/TodoList.vue
src/components/common/DetailsList.vue
src/views/Correction.vue

* Previous Pr comments addressed.

Corrections Dashboard: Previous comments addressed

---

src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/TodoList.vue

* Implements resuming draft correction filings.
* Implements tags on the original filings corrected and when there is a pending correction.

#2615 Corrections Dash P3: Resume Correction Drafts

---

src/components/Dashboard/TodoList.vue

* Implemented Priority tag for correction header.
* Code clean up.

#2615 - Corrections - Implemented Priority and Cleanup

---

src/components/Dashboard/TodoList.vue
src/components/common/DetailsList.vue
src/enums/filingStatus.ts

* Implements changes to correction filings status

Updates to Status

---

src/components/common/StaffPayment.vue
src/components/common/SummaryCertify.vue
src/components/common/SummaryStaffPayment.vue
src/views/StandaloneDirectorsFiling.vue
tests/unit/AnnualReport.spec.ts
tests/unit/DetailComment.spec.ts
tests/unit/StaffPayment.spec.ts
tests/unit/StandaloneDirectorsFiling.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts
tests/unit/TodoList.spec.ts

- updated Summary Staff Payment component
- also fixed/cleaned up some related styling
- commented out some 'expects' in Todo List (to be fixed in /bcgov/entity#2827)
- fixed broken unit tests in other components

correction filing (Summary Staff Payment + unit tests)

---

src/components/Dashboard/FilingHistoryList.vue
src/components/common/DetailsList.vue

*Issue #:* /bcgov/entity#2830
- fixed duplicate comment in Details List
- fixed unhandled flag in Filing History List

fixed dashboard bugs

---

src/components/Dashboard/FilingHistoryList.vue
src/views/Correction.vue

*Issue #:* /bcgov/entity#2830
- don't assign initial Corrected By
- added receipt code for correction filings
- fixed affix scrolling behaviour

changed Correct By behaviour + fixed receipt bug + fixed affix

---

src/components/Dashboard/FilingHistoryList.vue

*Issue #:* /bcgov/entity#2830
- check for any documents before de-referencing array

fixed highlight de-ref bug

---

src/assets/styles/layout.scss
src/components/common/Certify.vue
src/components/common/StaffPayment.vue
src/components/common/SummaryStaffPayment.vue
src/views/AnnualReport.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue

*Issue #:* /bcgov/entity#2888
- fixed typos (in code comments)
- updated app max-width (per Jeremy, ie, same as auth-web)
- fixed AR fee summary scrolling
- fixed Staff Payment not valid when props are set
- tweaked some text fields to prevent element from overflowing its container
- added maxlength to RSN input for better usability

misc small UI fixes

---

src/components/common/Certify.vue
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue

*Issue #:* /bcgov/entity#2819
Text updates to Certify Correct sections

#2819-Certify-Correct-Text-Updates

---

src/components/common/DetailsList.vue
tests/unit/DetailsList.spec.ts
tests/unit/FilingHistoryList.spec.ts
tests/unit/TodoList.spec.ts

* Fixes Existing unit testing for components affected by Corrections
*Implements or updates unit tests for the following:*
* DetailsList ( new component )
* Filing History List
* ToDo List

#2615 corrections unit tests

---

src/components/common/Directors.vue
src/store/getters.ts
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue
tests/unit/AnnualReport.spec.ts
tests/unit/Correction.spec.ts
tests/unit/StaffPayment.spec.ts
tests/unit/StandaloneDirectorsFiling.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts
tests/unit/SummaryStaffPayment.spec.ts

*Issue #:* /bcgov/entity#2829
- implemented Summary Staff Payment unit tests
- updated Staff Payment unit tests
- replaced some strings with types
- implemented Correction unit tests
- updated other filings unit tests

implemented corrections related unit tests

---

src/App.vue
src/components/Dashboard/TodoList.vue
src/store/actions.ts
src/store/mutations.ts
src/store/state.ts
src/views/Dashboard.vue

*Issue #:* /bcgov/entity#1889
- replaced store variable + watcher with event mechanism

change to reload dashboard using event

---

jest.config.js
package-lock.json
package.json

*Issue #:* /bcgov/entity#3070
- updated sbc-common-components to v.2.1.19
- updated Jest config to fix errors

updated sbc-common-components

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#3043
- updated to latest common components to pick up config key name change

updated to latest common components to pick up config key name change

---

src/App.vue

*Issue #:* /bcgov/entity#3165, /bcgov/entity#3169
- always init current date when app is created
- always listen for reload event when app is created
- fetch data when app is mounted only if authenticated
- added app destroy handler for completeness

fixed Current Date not being set

---

src/main.ts
src/views/auth/Signin.vue

*Issue #:* /bcgov/entity#3163
- added TokenService to handle refreshes
- initialized after signin success (ie, once tokens are populated)

added token refresh service

---

src/App.vue
src/mixins/namex-request-mixin.ts
src/views/auth/Signin.vue

*Issue #:* /bcgov/entity#3163
- moved token service from Signin to App so it exists for lifetime of app
- deleted temporary expiration date override

fixed token service init

---

.gitignore
src/App.vue
src/components/EntityInfo.vue
src/main.ts
src/mixins/namex-request-mixin.ts
src/router.ts
src/routes.ts
tests/unit/Dashboard.spec.ts
tests/unit/EntityInfo.spec.ts

*Issue #:* /bcgov/entity#3105
- also made some changes as in Business Create UI
- also misc cleanup

added tests for Entity Info

---

src/components/Dashboard/AddressListSm.vue
src/components/Dashboard/DirectorListSm.vue
src/views/Dashboard.vue
tests/unit/AddressListSm.spec.ts
tests/unit/Dashboard.spec.ts
tests/unit/DirectorListSm.spec.ts

*Issue #:* /bcgov/entity#3107, /bcgov/entity#3108
- Updated dashboard to show address and directors list for NRs
- Update dashboard to disable change address / change directors buttons for NRs without a completed filing
- Update Address list component to show 'Complete your filing to display'
- Update Directors list component to show 'Complete your filing to display'
- Updated Dashboard unit tests
- Updated Address list unit tests
- Updated Director list unit tests

3107, 3108

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
tests/unit/TodoList.spec.ts

*Issue #:* /bcgov/entity#3101
- changed pending status icon to alert
- applied colours to pending, error and paid status icons
- added missing payment token code to incorp apps and corrections
- added incorp app unit test
- updated sbc-common-components to 2.1.27 for AUTH_URL fix
- updated app version to 2.10.0
- added unit tests for NR and Incorp App actions

Todo List for draft incorp app

---

src/components/Dashboard/TodoList.vue
tests/unit/TodoList.spec.ts

*Issue #:* /bcgov/entity#3101
- added View/Hide Details to some buttons (per discussion with Scott)
- consolidated button styles

updated Todo List buttons

---

src/components/common/NameRequestInfo.vue

*Issue #:* /bcgov/entity#3106
The layout in dev seems to be a bit different from what I see in local for many components. For todo list NR in particular, the icon position looks a bit off. After trying the styles in dev, the one in this PR looks ok.

Fix for alignment issue in dev

---

package-lock.json
package.json
public/config/configuration.json
src/common/FeatureFlags.ts
src/main.ts
src/utils/fetch-config.ts
src/views/Dashboard.vue

*Issue #:* /bcgov/entity#2596
- removed old library ld-vue
- updated to use launchdarkly-js-client-sdk (same as create ui)
- added FeatureFlags class
- added basic logic to block the app from loading up if it is an NR

2596 - launchdarkly clean up and basic logic

---

src/App.vue
src/assets/styles/overrides.scss
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/PaperFiling.vue
src/components/Dashboard/PendingFiling.vue
src/components/Dashboard/TodoList.vue
src/components/common/DetailsList.vue
src/components/common/ErrorContact.vue
src/components/dialogs/CancelPaymentErrorDialog.vue
tests/unit/Dashboard.spec.ts
tests/unit/DetailsList.spec.ts
tests/unit/ErrorContact.spec.ts
tests/unit/FilingHistoryList.spec.ts
tests/unit/PaperFiling.spec.ts
tests/unit/PendingFiling.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts
tests/unit/TodoList.spec.ts

*Issue #:* /bcgov/entity#3411
- added subtitle for PAID (vs COMPLETED) status
- implemented Filing Pending details
- improved Filings list expansion logic
- fixed Todo list expansion logic
- fixed Filings drop-down menu style
- cleaned up expansion buttons
- cleaned up layout and styles
- created some new sub-components
- added unit tests
- modernized some unit tests

new status + unit tests for Filings List

---

tests/unit/FilingHistoryList.spec.ts

fixed lint errors

---

src/components/Dashboard/TodoList.vue

fixed logic error

---

src/mixins/namex-request-mixin.ts

This is the same fix done in Create UI to handle a conditionally approved NR. In this scenario, the NR's state is "conditional" and the Consent Flag is not "received". Our app assigns a state of "need consent" so we can display the appropriate message in a dialog.

fixed NR Conditional/Need Consent logic

---

src/components/Dashboard/TodoList.vue
src/components/dialogs/BcolErrorDialog.vue
src/components/dialogs/index.ts
src/mixins/bcol-mixin.ts
src/mixins/index.ts
src/views/AnnualReport.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue
tests/unit/AnnualReport.spec.ts
tests/unit/BcolErrorDialog.spec.ts
tests/unit/StandaloneDirectorsFiling.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts
tests/unit/TodoList.spec.ts

initial commit

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/common/NameRequestInfo.vue
src/views/Dashboard.vue
src/views/StandaloneDirectorsFiling.vue
tests/unit/AnnualReport.spec.ts
tests/unit/BcolErrorDialog.spec.ts
tests/unit/Dashboard.spec.ts
tests/unit/StandaloneDirectorsFiling.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts
tests/unit/TodoList.spec.ts

*Issue #:* /bcgov/entity#2759
- first commit: fixed latent NR-related unit test warnings
- second commit: fixed latent BCOL-related unit test warnings
- third commit:
- fixed BCOMP COA pending filings check
- fixed pending chip style
- fixed latent lint errors
- fourth commit: updated app version

fixed BCOMP COA issues, etc

---

src/App.vue

*Issue #:* /bcgov/entity#3620
(related to PR https://github.com/bcgov/business-filings-ui/pull/74)
- although new code was added, the old code was accidentally left in
- the first (old) code block is not within a try...catch block and thus fails; the second (new) code block is not executed
- in this PR I simply deleted the old code

removed duplicate code from merge snafu

---

tests/unit/App.spec.ts

*Issue #:* /bcgov/entity#3499
- deleted unexpected trailing comma

fixed lint error

---

src/components/dialogs/NameRequestAuthErrorDialog.vue

*Issue #:* /bcgov/entity#3499 (tweak)
- updated error message (per Scott)

updated invalid IA/URL dialog message

---

package-lock.json
package.json

*Issue #:* /bcgov/entity
* Updates SBC Common Components dependency to the latest version.

Updated Common Components Dependency

---

src/components/Dashboard/FilingHistoryList.vue
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#3597
- update report functions to use documents list from legal-api

3597 - update to use documents list from legal api

---

src/components/Dashboard/FilingHistoryList.vue

Unable to load receipt for a FED or paid status numbered company

---

src/components/Dashboard/TodoList.vue

remove extra subtitle if there is a bcol error on payment

---

src/App.vue

*Issue #:* /bcgov/entity#3922
Added 'PENDING' state in addition to 'DRAFT' state to populate tasks list
Note: Cancel Payment breaks in the API and we have to discuss the things to do incase of cancel payment. Displaying the item in the list and resuming payment is taken care of in this

Show Pending Incorporation app in todo list

---

package-lock.json
package.json
src/assets/styles/theme.scss
src/components/Dashboard/LegalObligation.vue
src/store/getters.ts
src/views/Dashboard.vue
tests/unit/LegalObligation.spec.ts

*Issue #:* /bcgov/entity#3828
Added legal obligation section in filing dashboard
Added tests

Filings dashboard - Legal Obligation

---

src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/LegalObligation.vue
tests/unit/LegalObligation.spec.ts

*Issue #:* /bcgov/entity#4026, /bcgov/entity#4033
Bug fixes 
Hide Legal Obligation for a temp reg no with a completed incorporation filing

Bug fixes + Code to hide legal obligation for temp reg number 

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#4044
* Updated Common Components dependency in Filings UI.

Updated Common Component Dependency

---

src/components/Dashboard/LegalObligation.vue

Text changes in legal obligation

---

src/components/Dashboard/FutureEffectiveFiling.vue
tests/unit/FutureEffectiveFiling.spec.ts

*Issue #:* /bcgov/entity#4072
- update future effective filing component text for when there is no entity name (Numbered Benefit Company)

4072 - future effective filing test update

---

package-lock.json
package.json
src/main.ts
src/utils/fetch-config.ts

*Issue #:* /bcgov/entity#4126
- display alert only if app error isn't due missing ID
- updated app version to 2.13

conditionally skip app startup alert

---

Jenkinsfiles/build.groovy

add ochiu to pipeline permissions

---

src/main.ts
src/utils/fetch-config.ts

*Issue #:* /bcgov/entity#4126
- new fix since transpiled code isn't recognizing extended Error class
ref: https://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript

conditionally skip app start on alert (rework)

---

package-lock.json
package.json

* Rolling Back SBC Common Component Dependency until POST Tuesdays Release.

SBC-Rollback

---

src/mixins/bcol-mixin.ts
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue

*Issue #:* /bcgov/entity#3685
*Issue #:* /bcgov/entity#4093

fix 3685 and 4093  - filings UI

---

public/index.html
src/mixins/common-mixin.ts
tests/unit/EntityInfo.spec.ts
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#4137
* Updated the Page Title to 'BC Business Registry'.
* Added check in corpNum getter to use the Entity name when it's present. 
* Updated unit tests

Fix for Default title

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#4085
* Updated Common Components dependency to the latest.

Updated SBC Common Components Dependency

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/views/Dashboard.vue
tests/unit/TodoList.spec.ts

*Issue #:* /bcgov/entity#2824
* Fixed Bcomp annual report Due Date being the same date for all of the pending Annual Reports.
* Fixed UI bug where checkbox selection was selecting multiple checkboxes in pending Annual Reports.
* Fixed UI bug where grey overlay was triggered on box selection.
* Fixed console error from `tempRegNumber` not being defined on the vue instance.
* Style / UI Tweaks.
* Updated Unit tests.

#2824 Bcomp AR Bug Fixes

---

src/components/Dashboard/TodoList.vue
tests/unit/TodoList.spec.ts

*Issue #:* /bcgov/entity#4145
- updated "contact us" text for consistency
- simplified AR subtitle case
- added IA subtitle case (which is mutually exclusive with other cases)
- deleted some obsolete NR code
- added unit tests

fixed double subtitles in Todo list

---

src/components/common/Directors.vue
src/components/common/OfficeAddresses.vue

*Issue #:* /bcgov/entity#1808 & /bcgov/entity#2338
* Small UI Bug Fixes.
* Bug from #2338 was fixed prior but assigned to this PR so it can be verified and QA'd and moved along with ticket #1808.
* Small no wrap applied to checkbox label.

Filings UI Fixes

---

package-lock.json
package.json
src/App.vue

updated sbc-common-components dependency to 2.2.9

---

src/utils/fetch-config.ts

*Issue #:* /bcgov/entity#4381
* Updated the request header option `cache-control` to `no-store` to prevent the network responses to be cached in the browser.

Config Request Header Update

---

src/enums/filingCodes.ts
src/mixins/resource-lookup-mixin.ts
src/resources/business-config.ts
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue
tests/unit/Directors.spec.ts

*Issue #:* /bcgov/entity#4486
* Updated Fee Codes and logic for Address and Director change filings to handle both Bcomps and Coops codes.
* Fixed unit tests console errors.

4486 BCOMP Fee Codes

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#4550
* Upgraded SBC Common Components Dependency

Upgraded SBC Version

---

src/views/auth/Signin.vue

- updated signin complete event from sbc-common-component

updated signin complete event from sbc-common-component

---

package-lock.json
package.json
public/config/configuration.json
src/axios-auth.ts
src/main.ts
src/utils/fetch-config.ts

*Issue #:* /bcgov/entity#3933
- configure sentry 
- sends entry messages on errors for api requests

#3933 configure sentry, sends entry messages on errors for api requests

---

src/common/FeatureFlags.ts
src/components/Dashboard/TodoList.vue
src/views/Dashboard.vue

*Issue #:* /bcgov/entity#4372
- removed obsolete feature flag default
- removed obsolete Coming Soon card from Todo List
- removed obsolete tooltips from addresses and directors change buttons

removed obsolete Coming Soon code

---

package-lock.json
package.json
src/App.vue
src/main.ts
vue.config.js

**Not ready to merge -- need sbc-common-components 2.3.3 (still in PR).**
*Issue #:* /bcgov/entity#2555
- added app friendly name
- injected env variables for app name and version
- pass app name-version string to Sbc Footer (requires next sbc-common-components version)
- also updated misc dependencies
*Screenshots:*
The information icon:
The tooltip (when hovering over the icon):

added app info to footer

---

Jenkinsfiles/build.groovy

- fixed context directory
- removed Ody from submitters list

Updated build.groovy

---

src/mixins/date-mixin.ts
src/views/AnnualReport.vue
src/views/StandaloneDirectorsFiling.vue

*Issue #:* /bcgov/entity#4536
- Common function to convert Local Date to UTC DateTime
- Converted local date to utc datetime in annual-report and standalone-directors-filing

Corrected effectiveDate and annualReportDate

---

public/config/configuration.json
src/App.vue
src/utils/fetch-config.ts

*Issue #:* /bcgov/entity#4795
* Implemented common component `PaySystemAlert` to monitor and display issues with PAYBC on the entities dashboard.
*Notes: *
* This work requires OS config updates for dev/test/prod for the PayBc status url. This will be done immediately, and should be complete before merge.

Implemented Pay System Alert

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#4795
* Upgrade SBC dependency to include changes to Pay Alert Banner

Upgraded SBC Common Components Dependency

---

src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/TodoList.vue
src/main.ts
src/utils/feature-flags.ts
src/utils/index.ts
src/views/Dashboard.vue
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#4514
- disabled IA correction menu item according to FF
- moved feature flags file to utils/
- added new feature flags
- deleted obsolete code
- added Business ID as route parameter to Edit UI URL

added FF + updated Edit UI URL

---

src/components/Dashboard/FilingHistoryList.vue

Adding the divider in Alterations

---

src/interfaces/correctionFiling-interface.ts
src/mixins/filing-mixin.ts
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#4646
* fixed IA Correction filing structure and interface

Fixed IA Correction Structure

---

src/components/Dashboard/FilingHistoryList.vue
tests/unit/FilingHistoryList.spec.ts

5085 Correction, update UI to display new document list

---

src/enums/legalTypes.ts
tests/unit/AddressListSm.spec.ts
tests/unit/AnnualReport.spec.ts
tests/unit/App.spec.ts
tests/unit/CODDate.spec.ts
tests/unit/Dashboard.spec.ts
tests/unit/DirectorListSm.spec.ts
tests/unit/Directors.spec.ts
tests/unit/EntityInfo.spec.ts
tests/unit/FilingHistoryList.spec.ts
tests/unit/OfficeAddresses.spec.ts
tests/unit/StandaloneDirectorsFiling.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts
tests/unit/SummaryDirectors.spec.ts
tests/unit/SummaryOfficeAddresses.spec.ts
tests/unit/TodoList.spec.ts

*Issue #:* /bcgov/entity#5048
- Enum BC to BEN
- Test fixes

5048: Legal Type for Benefit Company from BC to BEN

---

src/enums/filingCodes.ts
src/views/AnnualReport.vue
src/views/StandaloneDirectorsFiling.vue

*Issue #:* /bcgov/entity#5126
Updates to use the correct code for Benefit Company Free Director Change

Fee code fix for Benefit Company Director Change

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#4875
- updated sbc-common-components to 2.3.7
- update version to 3.3.0

updated sbc-common-components dependency and my version number

---

src/components/Dashboard/FilingHistoryList.vue

*Issue #:* /bcgov/entity#5355
- filingDate instead of correctedFilingDate in FilingHistoryList

Correct time does not appear for Detail after filing a correction

---

src/App.vue
src/assets/styles/base.scss
src/components/Dashboard/AddressListSm.vue
src/components/Dashboard/DirectorListSm.vue
src/components/Dashboard/FilingHistoryList.vue
src/components/EntityInfo.vue
src/components/common/Directors.vue
src/components/common/OfficeAddresses.vue
src/components/common/SummaryDirectors.vue
src/components/common/SummaryOfficeAddresses.vue
src/mixins/common-mixin.ts
src/mixins/index.ts
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue
tests/unit/common-mixin.spec.ts

*Issue #:* /bcgov/entity#5434
- added alternate loading spinner (grayed out, no text)
- added Show Spinner event
- changed transitions for correct in/out behaviours
- deleted obsolete base styles
- show spinner while creating IA Correction filing
- renamed ObjectMixin -> CommonMixin
- added unit tests

added spinner during IA correction creation + misc fixes

---

.github/workflows/cd.yml

*Issue #:* /bcgov/entity#5626
Update for deprecating set-env command of GHA.

Update for set environment variables issue of GHA.

---

src/App.vue
src/components/common/Directors.vue
src/components/common/SummaryOfficeAddresses.vue
src/mixins/common-mixin.ts
src/mixins/legal-api-mixin.ts
src/store/getters.ts
src/views/AnnualReport.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue
tests/unit/AGMDate.spec.ts
tests/unit/AnnualReport.spec.ts
tests/unit/CODDate.spec.ts
tests/unit/Correction.spec.ts
tests/unit/Dashboard.spec.ts
tests/unit/Directors.spec.ts
tests/unit/OfficeAddresses.spec.ts
tests/unit/StaffPayment.spec.ts
tests/unit/StandaloneDirectorsFiling.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts
tests/unit/SummaryOfficeAddresses.spec.ts
tests/unit/SummaryStaffPayment.spec.ts
tests/unit/TodoList.spec.ts

*Issue #:* /bcgov/entity#2461
- fixed Directors unit tests
- fixed AR unit tests
- fixed COD unit tests
- fixed COA unit tests
- fixed Corrections unit tests
- updated some element names/classes/ids
- initialized some properties
- removed some obsolete test config overrides
- updated some test workaround comments
- moved isJestRunning to getters
- ignored some $refs when Jest is running to avoid undefined errors due to shallow mount

updated unit tests

---

src/components/Dashboard/LegalObligation.vue
tests/unit/LegalObligation.spec.ts

* Adds BCOMP condition to Legal obligations verbiage

Updated Condition for legal Obligations

---

package-lock.json
package.json
src/App.vue
src/components/Dashboard/FilingHistoryList.vue
src/components/EntityInfo.vue
src/main.ts
src/mixins/legal-api-mixin.ts
src/utils/feature-flags.ts
src/views/AnnualReport.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue
tests/unit/AnnualReport.spec.ts
tests/unit/App.spec.ts
tests/unit/StandaloneDirectorsFiling.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts

*Issue #:* /bcgov/entity#5591
- updated version to 3.5.2
- added code to fetch user info and update LD
- updated FF code to latest
- changed AR filing to use isPaymentActionRequired flag
- changed COD to use isPaymentActionRequired flag
- changed COA to use isPaymentActionRequired flag

redirect to Pay URL depending on payment flag

---

src/components/Dashboard/FilingHistoryList/CompletedIa.vue
src/components/Dashboard/TodoList.vue
tests/unit/TodoList.spec.ts
tests/unit/TodoList2.spec.ts

*Issue #:* /bcgov/entity#5802
- added check for pay-error class
- combined pending status blocks
- replaced array filter with find
- very minor cleanup
- created new test file for template-first tests (very incomplete)

todo list tweaks and prep for further unit tests

---

package-lock.json
package.json
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue

*Issue #:* /bcgov/entity#6202
- updated version to 3.5.5
- fixed timing issue in Annual Report
- fixed timing issue in Correction
- fixed timing issue in COD
- fixed timing issue in COA

fixed filing timing issues

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#6197
- updated app version to 3.6.0

updated app version

---

src/components/Dashboard/FilingHistoryList.vue
src/views/AnnualReport.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue

*Issue #:* /bcgov/entity#6197
- get AR year from AR Filing Year if available, otherwise get year from Annual Report Date as before

bug fix for AR date

---

package-lock.json
package.json
src/App.vue
src/mixins/resource-lookup-mixin.ts

*Issue #:* /bcgov/entity#6475
Although the subject bug was due to invalid data in the database, I did the following to prevent future like errors:
- added console error if corp type doesn't match legal type
- added defensive checks to Resource Lookup code
- updated app patch version

added defensive code to prevent future errors

---

package-lock.json
package.json
public/index.html
src/components/Dashboard/FilingHistoryList.vue
src/components/dialogs/CoaWarningDialog.vue
src/mixins/date-mixin.ts
src/views/Dashboard.vue
tests/unit/FilingHistoryList.spec.ts
tests/unit/date-mixin.spec.ts

- updated UTC -> Pacific method (per BC Gov web style guide)
- deleted unneeded date-time-format-timezone script
- bumped app version to 3.8.3

misc date/time updates to keep in sync with other apps

---

package-lock.json
package.json

- updated vue-test-utils-helpers import

Updated vue-test-utils-helpers import

---

package-lock.json
package.json
tests/unit/EntityInfo.spec.ts
tests/unit/FilingHistoryList.spec.ts

- imported new Corp Type Module (to pick up missing "BC" from a desc)
- updated some unit tests accordingly

Imported updated Corp Type Module

---

src/components/EntityInfo.vue

*Issue #:* /bcgov/entity#7103
* Enabled BEN Alterations.
* Most of the work here was testing and verifying BEN alterations, which went smoothly once we were able to create `Change of Name` NR's.

Enabled BEN alterations and verified

---

.github/workflows/cd.yml
Dockerfile
Makefile
devops/vaults.json

1. Switch master branch to main branch;
2. Migrated the environments to 1password;
3. Modify CD flow on makefile;
4. Modify CI/CD GHA scripts;

Switch master to main branch and  update CICD flow.

---

package-lock.json
package.json
src/App.vue
src/components/Dashboard/TodoList.vue
src/components/EntityInfo.vue
src/store/getters.ts
tests/unit/App.spec.ts
tests/unit/EntityInfo.spec.ts
tests/unit/TodoList.spec.ts

*Issue #:* /bcgov/entity#6923
Show text & disable resuming alteration if not in good standing

changes for showing in good standing

---

nginx.conf
package-lock.json
package.json
vue.config.js

*Issue #:* /bcgov/entity#7263
- added nginx config to disable index.html caching
- updated sbc-common-components dependency
- added workbox config to exclude precaching JSON files

Updated sbc-common-components dependency + updated caching config

---

package-lock.json
package.json
src/assets/styles/base.scss
src/assets/styles/layout.scss
src/components/Dashboard/FilingHistoryList.vue
src/views/Dashboard.vue
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#7196
* Allows scrolling on Filings History List and Directors List.
* Added `Effective as of Date` to filings history list when present.
* Minor UI/style adjustments.
* Updates unit testing.
*Note:*
* Hide white space changes to easier review. Adding a wrapper creates a large diff where it actually pretty small :) 
* Does NOT contain any data restructure as noted in the ticket, as the API work is still pending.

Scrollable sections and UI updates

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue

*Issue #:* /bcgov/entity#4389
* Condition to hide receipts on the staff filings.

Hide receipts on Staff Filings

---

package-lock.json
package.json
src/components/dialogs/AddStaffNotationDialog.vue

*Issue #:* /bcgov/entity#4388
- Removed css margin rule

4388 - Small fix for layout

---

tests/unit/AddStaffNotationDialog.spec.ts
tests/unit/StaffNotation.spec.ts

*Issue #:* /bcgov/entity#4388
- Removed test warnings

4388 - Fixed unit test warnings

---

package-lock.json
package.json
src/components/dialogs/AddStaffNotationDialog.vue

*Issue #:* /bcgov/entity#4388
- Increased textarea rows to 5; 
- decreased spacing between elements.

4388 - Small layout fixes

---

package-lock.json
package.json
src/components/Dashboard/StaffNotation.vue
src/views/Dashboard.vue

*Issue #:* /bcgov/entity#4388
- Postioned label aligned to the header

4388 - UX Assurance - Postioned label aligned to the header

---

package-lock.json
package.json
src/components/dialogs/AddStaffNotationDialog.vue

4389 - UX - Removed spinner from Cancel button on save

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/enums/filingNames.ts
src/mixins/enum-mixin.ts
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#4389
* Updated Verbiage for staff only filings.

Filings History - UX Updates

---

package-lock.json
package.json
src/components/Dashboard/StaffNotation.vue

*Issue #:* /bcgov/entity#7759
* Added pointer to Staff Filing activator on hover.

Added cursor to Staff Filing btn

---

package-lock.json
package.json
src/components/Dashboard/StaffNotation.vue

*Issue #:* /bcgov/entity#7765
- Removed transparency for v-dialog scrollbar

7765 - Removed transparency for v-dialog scrollbar

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#6682
Fix bug and disable browser autocomplete on address input

Update sbc-common-components version

---

package-lock.json
package.json

This PR was merged prematurely.
Reverts bcgov/business-filings-ui#217

Revert "Update sbc-common-components version"

---

package-lock.json
package.json
public/config/configuration.json
src/utils/fetch-config.ts

*Issue #:* /bcgov/entity#7694
- added Auth Api Config workaround
- added local configuration

Added auth config key loading

---

package-lock.json
package.json

Update sbc-common-component version number
*Issue #:* /bcgov/entity#6682
Update sbc-common-component version number

Update sbc-common-component version number

---

package-lock.json
package.json
src/App.vue
src/components/AnnualReport/ARDate.vue
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/TodoList.vue
src/components/common/DetailsList.vue
src/components/common/NameRequestInfo.vue
src/mixins/date-mixin.ts
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue
tests/unit/App.spec.ts
tests/unit/Correction.spec.ts
tests/unit/FilingHistoryList.spec.ts
tests/unit/TodoList.spec.ts
tests/unit/date-mixin.spec.ts

*Issue #:* /bcgov/entity#7079
- updated component name style in some templates
- updated and renamed data mixin functions
- updated dates and times in Filing History List
- fixed BCOMP AR Date conversion bug
- deleted unnecessary dialog
- updated date mixin for consistency with other UIs (and correct API-Pacific conversions)
- updated app minor version

Updated date conversions/display (mixin, etc)

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#7079
- updated staff comment import (to use new date mixin)

Updated Staff Comment component import

---

package-lock.json
package.json
src/App.vue

*Issue #:* /bcgov/entity#7785
* Updated the list of supported entities in the filings ui. 
*.Updated version.

Updated supported entity types

---

.github/workflows/ci.yml
Dockerfile
k8s/templates/bc.yaml

*Issue #:* /bcgov/entity#8609
- Updated node version

8609 - Updated node version

---

package-lock.json
package.json
src/mixins/name-request-mixin.ts

8922 update to use NR State - CONSUMED, EXPIRED

---

package-lock.json
package.json
src/App.vue
tests/unit/App.spec.ts

9049 validate NR only when IA filing is in DRAFT or PENDING status

---

src/mixins/name-request-mixin.ts

*Issue #:* /bcgov/entity#9199
* Small update to take/use the NR type dynamically.

Update to use Nr type dynamically

---

package-lock.json
package.json
src/enums/incorporatorTypes.ts
tests/unit/App.spec.ts
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#6742
- Changed organization terms; 
- Fixed tests;
- Updated version

6742 - Changed organization terms

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/interfaces/api-filing-interface.ts
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#9869
- fixed data object name
- updated interface
- app version: 4.0.14

9869 Fixed staff filing details

---

package-lock.json
package.json
src/enums/dissolutionTypesNames.ts
src/mixins/filing-mixin.ts

*Issue #:* /bcgov/entity#8838
* Applied `VOLUNTARY` dissolution type to draft filing to meet schema requirements. 
* This is potentially going to change depending on outcomes from API tickets/discussions
re: https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/7635

Updated Dissolution Type

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/TodoList.vue

- removed unnecessary padding around todo list items
- removed unnecessary padding above history list items
- app version: 4.0.17

Fixed some whitespace

---

package-lock.json
package.json
src/App.vue
src/components/AnnualReport/AGMDate.vue
src/components/AnnualReport/ARDate.vue
src/components/Dashboard/TodoList.vue
src/components/StandaloneDirectorChange/CODDate.vue
src/components/common/Directors.vue
src/components/common/NameRequestInfo.vue
src/components/dialogs/AddStaffNotationDialog.vue
src/enums/nameRequestStates.ts
src/interfaces/form-interface.ts
src/interfaces/state-interface.ts
src/mixins/date-mixin.ts
src/mixins/name-request-mixin.ts
src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
src/views/AnnualReport.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue
tests/unit/ARDate.spec.ts
tests/unit/date-mixin.spec.ts
tests/unit/enum-mixin.spec.ts
tests/unit/mixin-tester.vue

*Issue #:* /bcgov/entity#10173
Commit 1:
- fixed broken NR formatted expiration date 
- updated expires text logic to match new date mixin responses
- updated date mixin to compare dates as of 12:00am
- app version: 4.0.19
Commit 2:
- renamed a NR mixin getter for consistency 
- added missing NR states
- deleted obsolete NR enum
- updated form interface for consistency
- added approved name check to NR validity method
- fixed potential error in approved name check
Commit 3:
- now store JS date from server 
- renamed compareDates -> compareYyyyMmDd
- removed getCurrentDate from Date Mixin
- renamed formatDateString -> formatYyyyMmDd
- renamed latestDate -> latestYyyyMmDd
- formatted NR expiry date as long date-time string
- renamed …

10173 Updated NR expiry date logic

---

package-lock.json
package.json
src/App.vue
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/LegalObligation.vue
src/components/Dashboard/StaffNotation.vue
src/components/Dashboard/TodoList.vue
src/components/EntityInfo.vue
src/enums/allowableActions.ts
src/enums/index.ts
src/interfaces/state-interface.ts
src/mixins/allowable-actions-mixin.ts
src/mixins/index.ts
src/store/getters.ts
src/store/state.ts
src/views/Dashboard.vue
tests/unit/Dashboard.spec.ts
tests/unit/EntityInfo.spec.ts
tests/unit/FilingHistoryList.spec.ts
tests/unit/LegalObligation.spec.ts
tests/unit/allowable-actions-mixin.spec.ts
tests/unit/date-mixin.spec.ts
tests/unit/enum-mixin.spec.ts
tests/unit/mixin-tester.vue

*Issue #:* /bcgov/entity#7635 and /bcgov/entity#9350
The intent of these changes is to prepare the code (framework) for when the UI gets the list of allowable actions from the API (ie, that business logic will no longer exist in the UI).
- created Allowable Actions mixin
- created Allowable Actions enum
- moved "allow" logic to new mixin
- created unit tests for new mixin
- updated other unit tests
- app version: 4.2.1
- also added commit to align Entity Info buttons vertically

7635 Implemented Allowable Actions mixin

---

package-lock.json
package.json
src/assets/styles/layout.scss
src/components/Dashboard/AddressListSm.vue
src/components/Dashboard/CustodianListSm.vue
src/store/getters.ts
src/views/Dashboard.vue

*Issue #:* /bcgov/entity#8822 and /bcgov/entity#9282
* Implemented Custodian of Records Accordion
* Global style updates 
* - Hidden scroll bars
* - Removed DASHBOARD title header
* Basic Getter placeholder for custodians

Custodian accordion + global updates

---

src/App.vue
src/interfaces/business-interface.ts

*Issue #:* /bcgov/entity#7635
- remove unneeded fallbacks for business fields
- added field to business interface

7635 minor cleanup

---

package-lock.json
package.json
public/index.html
src/components/AnnualReport/AGMDate.vue
src/components/Dashboard/FilingHistoryList/PendingFiling.vue
src/components/Dashboard/TodoList.vue
src/components/EntityInfo.vue
src/components/common/ContactInfo.vue
src/components/dialogs/NameRequestAuthErrorDialog.vue
src/components/dialogs/NotInGoodStandingDialog.vue
src/mixins/allowable-actions-mixin.ts
tests/unit/EntityInfo.spec.ts
tests/unit/NotInGoodStandingDialog.spec.ts
tests/unit/allowable-actions-mixin.spec.ts

*Issue #:* /bcgov/entity#10464
- reverted/updated some "BC Registries" changes 
- updated NIGS messages
- increased size of contact info (common)
- disabled HISTORICAL chip hover effect
- bolded HISTORICAL chip
- changed subtext colour
- don't allow Change Info when using temp id (ie, not bus id)
- updated Confirm Delete IA text
- add unit tests for NIGS dialog
- app version = 4.2.4

10464 Misc UXA fixes and updates

---

package-lock.json
package.json
src/App.vue
src/resources/BreadcrumbResources.ts
src/resources/breadcrumb-resources.ts
src/resources/index.ts

*Issue #:* /bcgov/entity#10232
* Updated version of BreadCrumb
* Added home crumb
* Capitalized Resource file

BreadCrumb Update

---

package-lock.json
package.json
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/Dashboard.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue

*Issue #:* /bcgov/entity#9530
- the Have Changes check was not prompting when Cancel was clicked
- navigating away from the page was triggering even after cancelling (no more outstanding changes)
- fixed for AR, COA, COD and CORR

9530 Fixed Have Changes check

---

package-lock.json
package.json
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue

*Issue #:* /bcgov/entity#9530
- fixed filing id not saved on pay error, which causes retry to fail
- app version = 4.3.2

9530 Fixed filing id not saved on pay error

---

devops/vaults.json
package-lock.json
package.json
public/config/configuration.json
src/App.vue
src/resources/BreadcrumbResources.ts
src/utils/fetch-config.ts

*Issue #:* /bcgov/entity#10747
* Added configuration for BCROS Home Url
* Updated Home Crumb for non-staff
*NOTE:* - The updated routes require additional in configuration in DEV, TEST, PROD ENV's to add the following:
Dev = https://yfthig-dev.web.app/
Test = https://www.bcregistry.daxiom.ca/
Prod = https://www.bcregistry.gov.bc.ca/

Updated Home crumb and config

---

package-lock.json
package.json

*Issue #:* /bcgov/entity#10922
* Updated common components version

Updated CC Version

---

package-lock.json
package.json
src/App.vue
src/components/common/DetailComment.vue
src/main.ts
src/views/auth/Signin.vue
src/views/auth/Signout.vue

*Issue #:* /bcgov/entity#10853
- initialize token service in main instead of App (needed to sync session before routing)
- redirect to BC Registry for login, then return here
- after logout, redirect to login page
- app version = 4.3.6

10853 Login and logout redirects

---

package-lock.json
package.json
src/App.vue
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/FilingHistoryList/CompletedIa.vue
src/components/Dashboard/TodoList.vue
src/components/EntityInfo.vue
src/components/common/Directors.vue
src/components/common/OfficeAddresses.vue
src/main.ts
src/mixins/date-mixin.ts
src/resources/BreadcrumbResources.ts
src/resources/business-config.ts
src/utils/feature-flags.ts
src/utils/fetch-config.ts
src/utils/index.ts
src/utils/navigate.ts
src/views/AnnualReport.vue
src/views/Correction.vue
src/views/StandaloneDirectorsFiling.vue
src/views/StandaloneOfficeAddressFiling.vue
src/views/auth/Signin.vue
tests/unit/AnnualReport.spec.ts
tests/unit/Directors.spec.ts
tests/unit/EntityInfo.spec.ts
tests/unit/FilingHistoryList.spec.ts
tests/unit/StandaloneDirectorsFiling.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts
tests/unit/TodoList.spec.ts
tests/unit/fetch-config.spec.ts

*Issue #:* /bcgov/entity#10999
- stored account id in session
- created "navigate" function to automatically add accountid parameter
- replaced window.location.assign with new function
- fixed date/time conversions broken by Node 14
- updated breadcrumb resources to append account id
- fixed invalid URLs in unit tests
- app version = 4.3.7

10999 Handle account id sync

---

package-lock.json
package.json
src/mixins/allowable-actions-mixin.ts
src/utils/feature-flags.ts
tests/unit/allowable-actions-mixin.spec.ts

*Issue #:* /bcgov/entity#11042
* Updated implementation of Feature Flag implementation for Business Summary
* Updated unit testing

Updated Business Summary Feature Flag

---

package-lock.json
package.json
src/App.vue
src/components/Dashboard/TodoList.vue

*Issue #:* /bcgov/entity#11125
* Updated redirect url for Dissolutions Filing

11125 Dissolutions Route Update

---

src/mixins/date-mixin.ts

*Issue #:* /bcgov/entity#10774
Fixed NR Expiry Date decimal issue.

10774_fix_decimal_issue_nr_expiry

---

package-lock.json
package.json
src/mixins/date-mixin.ts
tests/unit/date-mixin.spec.ts

*Issue #:* /bcgov/entity#10774
Fix Expiry Date Decimal value to be rounded to nearest day - returns whole number

10774_ne_expiry_date_fix_decimal_issue

---

package-lock.json
package.json
src/components/EntityInfo.vue
src/mixins/allowable-actions-mixin.ts
src/store/getters.ts

*Issue #:* /bcgov/entity#10613
* Small QOL update for Firms to redirect to the appropriate route when starting a Change Filing vs an Alteration Filing

Updated Firm Redirect

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/enums/filingNames.ts
src/enums/filingTypes.ts
src/interfaces/api-task-interface.ts

*Issue #:* /bcgov/entity#10613
* Implements handlers for Change of Registration Draft Filings

Support Change of Registration Drafts

---

package-lock.json
package.json
src/utils/fetch-config.ts

support fm identifier

---

package-lock.json
package.json
src/utils/fetch-config.ts

identifier fix

---

package-lock.json
package.json
src/utils/fetch-config.ts

*Issue #:* /bcgov/entity#309
* Updated identifier logic

Identifier Condition update

---

package-lock.json
package.json
src/App.vue
src/enums/roles.ts
tests/unit/App.spec.ts
tests/unit/legal-api-mixin.spec.ts

*Issue #:* /bcgov/entity#11898
* fixed role check to adhere to api update

Fixed Role Check

---

package-lock.json
package.json
src/components/Dashboard/LegalObligation.vue
src/components/Dashboard/TodoList.vue
src/components/EntityInfo.vue
src/components/common/NameRequestInfo.vue
src/mixins/allowable-actions-mixin.ts
src/store/getters.ts
tests/unit/FilingHistoryList.spec.ts
tests/unit/TodoList.spec.ts
tests/unit/date-mixin.spec.ts

*Issue #:* /bcgov/entity#9841
- updated entity description in Entity Info
- updated entity type description in Name Request Info
- ~used flex CSS to indent wrapped values in Name Request Info~ _reverted_
- fixed layout in Legal Obligation
- replaced mapGetters with @Getter in Legal Obligation
- updated registration title in Todo List
- replaced isFirm with isSoleProp and isPartnership
- updated browsers list
- misc cleanup
- app version = 4.4.0

9841 Misc updates for SP/DBA labels

---

.sonarcloud.properties

*Issue #:* /bcgov/entity#11663
* excluded resources folder from sonarcloud (since this folder is expected to contain redundant code)

excluded resources folder from SonarCloud

---

package-lock.json
package.json
src/components/dialogs/ConfirmDissolution.vue
src/store/getters.ts

*Issue #:* /bcgov/entity#12088
- imported latest sbc-common-components (2.4.46)
- app version = 5.0.2

12088 Imported latest sbc-common-components

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/TodoList.vue
src/components/common/NameRequestInfo.vue
src/interfaces/api-filing-interface.ts
src/interfaces/business-interface.ts
src/interfaces/index.ts
src/mixins/date-mixin.ts
src/mixins/filing-mixin.ts
src/mixins/name-request-mixin.ts
src/store/getters.ts
tests/unit/ARDate.spec.ts
tests/unit/AnnualReport.spec.ts
tests/unit/FilingHistoryList.spec.ts
tests/unit/NameRequestInfo.spec.ts
tests/unit/StandaloneOfficeAddressFiling.spec.ts
tests/unit/date-mixin.spec.ts

*Issue #:* /bcgov/entity#4781
- replaced incorrect use of "new Date()" with date mixins
- used new date types in API Filing interface
- used new date types in Business interface
- imported new date types
- created Name Request Info test suite
- fixed broken unit tests
- app version = 5.1.0

4781 Replaced incorrect use of "new Date()" with date mixins + used new date types

---

package-lock.json
package.json

Bumped app version to 3.1.6

---

package-lock.json
package.json
src/components/dialogs/ConfirmDissolution.vue
src/interfaces/dissolution-confirmation-interface.ts
src/resources/business-config.ts
tests/unit/ConfirmDissolution.spec.ts

*Issue #:* /bcgov/entity#11663
* fix confirm dissolution modal for SP/GP 

UI Confirm Dissolution Modal Fixes/11663

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/CompletedDissolution.vue
tests/unit/CompletedDissolution.spec.ts

*Issue #:* /bcgov/entity#12426
* UI changes for Statement of Dissolution Text
* Update effective date for SP/GP to only display the date with no time 
* Update act name to match confirm dissolution text

fix statement of dissolution text and update app version

---

package-lock.json
package.json
src/components/Dashboard/StaffNotation.vue
src/components/dialogs/AddStaffNotationDialog.vue
src/enums/filingNames.ts
src/enums/filingTypes.ts
src/mixins/enum-mixin.ts
tests/unit/AddStaffNotationDialog.spec.ts
tests/unit/enum-mixin.spec.ts

*Issue #:* /bcgov/entity#12092
* add 'Put Back On' option for historical companies and 'Administrative Dissolution' option for active companies to 'Add Staff Filing' drop-down
* implement modal for 'Put Back On' and 'Administrative Dissolution' 
**PR for Review - NOT ready for merge**

Create the filing for SP/GP/12092

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/TodoList.vue
src/interfaces/correction-filing-interface.ts
src/mixins/filing-mixin.ts
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#12392
**This is partial support only, and it's not perfect, but firm corrections are already broken so this isn't worse but it will unblock ongoing development.**
- added support to correct a Change of Registration filing and Registration filing
- fixed unit test
- app version = 5.2.0

12392 Added partial support to correct a Firm Registration or Change

---

package-lock.json
package.json
src/App.vue
src/interfaces/business-interface.ts
src/interfaces/state-interface.ts
src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
tests/unit/EntityInfo.spec.ts

*Issue #:* [/bcgov/entity#12300](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12300)
- Changed `complianceWarnings` to `warnings`

12300 Filing UI - update logic for displaying compliance warnings according to BE changes

---

package-lock.json
package.json
src/components/dialogs/AddStaffNotationDialog.vue

*Issue #:* /bcgov/entity#12092
* update button text on modal for file/save
* addition of local getter to check if filing type is Administrative Dissolution/Put Back
* update data sent to create Administrative Dissolution/Put Back On filing

Create filing sp gp/12092

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/FilingHistoryList/FiledLabel.vue

*Issue #:* /bcgov/entity#12093
* updates the ledger entry for Put Back On and Administrative Dissolution Filings in Recent Filing History List

Filing UI update the dashboard/12093

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/components/EntityInfo.vue

*Issue #:* /bcgov/entity#12629
Implemented Dissolution UX Fixes in entity-info header and drop down button.

Dissolution ux fixes/12629

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/components/EntityInfo.vue

*Issue #:* /bcgov/entity#12629
Clean-up for ticket #12629 as per PR #353 comments 

clean-up as per PR#353 comments

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/FilingHistoryList/CompletedRegistration.vue
src/interfaces/history-item-interface.ts
tests/unit/CompletedRegistation.spec.ts
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#12683
- add properties for registrations
- display appropriate section + component for complete registration
- add unit test
- app version  5.2.11

12683 Added panel for completed registrations

---

package-lock.json
package.json
src/mixins/filing-mixin.ts

*Issue #:* /bcgov/entity#12872
- fixed incorrect correctedFilingType
- app version = 5.2.13

12872 Fixed incorrect correctedFilingType

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/mixins/filing-mixin.ts
tests/unit/FilingHistoryList.spec.ts

*Issue #:* /bcgov/entity#12872
- temporarily disabled BEN IA corrections
- fixed firm correction object structure
- app version = 5.2.14

12872 Temporarily disabled BEN IA corrections + fixed firm correction object structure

---

package-lock.json
package.json
src/components/Dashboard/StaffNotation.vue

*Issue #:* /bcgov/entity#12957
Enable Administrative Dissolution from UI for BEN and COOP companies

Enable ad for bc coop/12957

---

package-lock.json
package.json
src/components/EntityInfo.vue

*Issue #:* /bcgov/entity#12629
Update tooltip transition to "fade" for icons in top header

update tooltip transition for header buttons

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue

*Issue #:* bcgov/entity#8225
- removed temporary AR code
- app version = 5.2.20

9225 Removed obsolete AR fallback code

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/FilingHistoryList/CompletedIa.vue
src/components/Dashboard/FilingHistoryList/CompletedRegistration.vue
src/components/Dashboard/FilingHistoryList/PendingFiling.vue
src/components/Dashboard/TodoList.vue
tests/unit/CompletedIa.spec.ts
tests/unit/CompletedRegistation.spec.ts
tests/unit/FilingHistoryList.spec.ts
tests/unit/PendingFiling.spec.ts

*Issue #:* bcgov/entity#12940 and bcgov/entity#12941
- misc cleanup to Filing History List component
- renamed "Manage Businesses" -> "My Business Registry"
- added sentence to Pending Filing component
- app version = 5.2.21

12940 and 12941 Misc UI changes + cleanup

---

package-lock.json
package.json
src/components/Dashboard/StaffNotation.vue

*Issue #:* /bcgov/entity#13266
* Enable creation of Put Back On filing for BEN and CP companies

allow put back on filing for BEN and CP

---

package-lock.json
package.json
src/components/DigitalCredentials/ChooseCredentials.vue
src/components/DigitalCredentials/DigitalWalletDownload.vue

*Issue #:* /bcgov/entity#13389
* Implements base UI for selecting the credential types.
* More to come here with regards to integration with the API. 
* Future: Request will be made upon selections to generate a QA.

Digital Credentials: Choose Type Component

---

package-lock.json
package.json
src/components/DigitalCredentials/ChooseCredentials.vue
src/components/DigitalCredentials/DigitalWalletDownload.vue
src/components/DigitalCredentials/ScanCredentials.vue
src/views/DigitalCredentials.vue

*Issue #:* /bcgov/entity#13388
* Implements Vue QR code generator
* Minor refactors for styling
* Added handling for selection events
* Basic UI (No api integration) for Scan Credentials
* Placeholder Success QR code

Scan Credentials + QR Generator

---

package-lock.json
package.json
src/enums/index.ts

*Issue #:* bcgov/entity#13170
- removed obsolete external enum
- app version = 5.5.1

13170 Removed obsolete external enum

---

package-lock.json
package.json
src/components/dialogs/AddStaffNotationDialog.vue

*Issue #:* /bcgov/entity#13633

Court Order bug fix

---

src/shims-tsx.d.ts
src/shims-vue.d.ts

*Issue #:* bcgov/entity#13674
- restored necessary type declarations

13674 Restored necessary type declarations

---

package-lock.json
package.json
src/components/DigitalCredentials/DigitalWalletDownload.vue
src/components/DigitalCredentials/RegisterWallet.vue

*Issue #:* /bcgov/entity#13389

13389 load qr code in svg to preserve image quality

---

package-lock.json
package.json
src/App.vue

*Issue #:* /bcgov/entity#13861
Remove d-flex from sbc-header. Update SBC-common-components to 3.0.3.

13861 - Update business-filings-ui to use sbc-common-components 3.0.3.

---

package-lock.json
package.json
src/resources/business-config.ts

*Issue #:* /bcgov/entity#13772
- fixed the typo

13772 Filing UI - Typos in the Obligations text

---

package-lock.json
package.json
src/assets/styles/theme.scss
src/components/DigitalCredentials/IssueCredentials.vue
src/main.ts

*Issue #:* /bcgov/entity#13390
* Update alert text colour as per UX for accessibility

Updated Alert Colour for Pilot Msg

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue

*Issue #:* /bcgov/entity#13950
- Fixed css style for `.todo-subtitle`

13950 Filings UI: broken formatting for draft Change of Company Information

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
tests/unit/TodoList1.spec.ts

*Issue #:* bcgov/entity#14007
- made details buttons mutually exclusive
- prioritized red details button over blue one
- cleaned up unit test
- app version = 5.7.13

14007 Fixed details buttons

---

package-lock.json
package.json
src/App.vue
src/components/Dashboard/FilingHistoryList.vue
src/mixins/allowable-actions-mixin.ts
src/mixins/resource-lookup-mixin.ts
src/resources/business-config.ts
src/store/getters.ts
tests/unit/FilingHistoryList1.spec.ts
tests/unit/allowable-actions-mixin.spec.ts

*Issue #:* bcgov/entity#14164
- deleted CCC workaround
- added new types in redirectThisFiling()
- added entity types to allowed corrections
- added "isCcc" to allowable actions mixin
- added resource objects for BC/CC/ULC
- added "isCcc" store getter
- app version = 5.7.19

14164 Fixed a few BC/CCC/ULC things

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/components/common/NameRequestInfo.vue
src/main.ts
src/utils/capitalize.ts
src/utils/format-phone-number.ts
src/utils/index.ts
tests/unit/NameRequestInfo.spec.ts
tests/unit/TodoList1.spec.ts

*Issue #:* bcgov/entity#13653
_Since I was already in Filings UI. I thought I'd clean up some lint/build warnings._
- deleted v-mask dependency
- replaced capitalize filter by util function
- replaced VMask by util function
- replaced orderBy filter by local getter
- implemented capitalize()
- imported formatPhoneNumber()
- misc cleanup
- app version = 5.7.21

13653 Fixed deprecated filter warnings

---

package-lock.json
package.json
src/App.vue
src/components/EntityInfo.vue
src/interfaces/name-request-interface.ts
src/mixins/name-request-mixin.ts
src/store/getters.ts
tests/unit/App.spec.ts

*Issue #:* bcgov/entity#14403
- changed isNrValid -> isNrInvalid and now returns error message
- app version = 5.7.24

14403 Added invalid NR messages logging

---

package-lock.json
package.json
public/config/configuration.json
src/main.ts
src/utils/fetch-config.ts

*Issue #:* bcgov/entity#14429
**These changes simply enable Hotjar in this project. Any sort of tracking or surveys or whatever needs to be configured and enabled on the Hotjar website. Until then, this change should have no impact, and I think it's a good idea to have this config from now on anyway.**
- added vue-hotjar package
- added Hotjar ID to config
- initialized Hotjar
- app version = 5.8.0

14429 Enabled Hotjar

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/enums/filingStatus.ts
src/mixins/enum-mixin.ts
tests/unit/enum-mixin.spec.ts

*Issue #:* bcgov/entity#14516
- added check for new pending status
- added logic to display "processing..." while checking status
- reduced retry count from 10 to 5 to finish faster
- updated list item button hover colour
- added new filing status enum value
- added new  mixin method + unit test
- app version = 5.8.1

14516 Fixed pending correct status + Cancel Payment style

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue

*Issue #:* bcgov/entity#14713
- added missing check for draft alteration
- simplified draft correction/alteration header (same as other drafts)
- simplified pending filing header
- now show conversion to reg users (same as corrections)
- now handle draft alteration like other drafts
- app version = 5.8.4

14713 Todo item cleanup (alteration, etc)

---

.github/workflows/cd.yml
.github/workflows/ci.yml

*Issue #:* /bcgov/entity/14257
Upgrade codecov and checkout version.

14257-Upgrade ci/cd

---

package-lock.json
package.json
src/views/Dashboard.vue
tests/unit/enum-mixin.spec.ts

*Issue #:* /bcgov/entity#15068
- now show Todo List even when historical
- lint fix
- app version = 5.9.6

15068 Fix Todo List not displayed when historical

---

package-lock.json
package.json
src/components/dialogs/AddStaffNotationDialog.vue

Signed-off-by: Kial Jinnah <kialjinnah@gmail.com>
*Issue #:* /bcgov/entity#13348

small wording change

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/EntityInfo.vue
src/interfaces/state-interface.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
tests/unit/EntityInfo.spec.ts
tests/unit/StaffNotation.spec.ts
tests/unit/store-actions.spec.ts

*Issue #:* bcgov/entity#15042
- added display fields to CCO filing
- added v-chip to Entity Info
- fixed reasonText bug
- deleted obsolete "reasonText"
- added safety check to getReasonText()
- fixed apiToDate bug
- updated "is limited restoration"
- added "is authorized continue out"
- added/fixed unit tests
- app version = 5.10.1

15042 New badge + misc fixes

---

package-lock.json
package.json
src/main.ts
src/store/Configuration/mutations.ts
src/utils/navigate.ts
src/utils/set-base-route-and-business-id.ts

*Issue #:* bcgov/entity#15742
- app version = 5.11.3a
- updated browsers list
- load configuration before checking business id
- set missing session storage variable
- check for empty URL before navigate

15742 Fixed missing session storage variable and config dependency

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/filings/LimitedRestoration.vue

*Issue #:* bcgov/entity#15864
- app version = 6.2.2
- fixed legal name property

15864 Fixed limited resto legal name

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/HeaderActions.vue
src/components/dialogs/FileCorrectionDialog.vue

*Issue #:* bcgov/entity#15870
- app version = 6.2.3
- fixed bug when creating draft correction filing

15870 Fixed invalid draft correction

---

.env.example
package-lock.json
package.json

*Issue #:* bcgov/entity#15842
- added common LD project key (Dev) to example env file
- app version = 6.2.4

15842 added new Dev LD key to sample config file

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/filings/ConsentContinuationOut.vue
src/services/date-utilities.ts
tests/unit/LedgerConsentContinuationOut.spec.ts

*Issue #:* /bcgov/entity#15971
Instead of this hot mess:
We have this:

15971 - fix ugly looking expiry date

---

package-lock.json
package.json
src/mixins/common-mixin.ts
src/views/ConsentContinuationOut.vue
tests/unit/ConsentContinuationOut.spec.ts

*Issue #:* /bcgov/entity#15051
- Yui's Comment: https://github.com/bcgov/entity/issues/15051#issuecomment-1518335264
- Short Demo:
https://user-images.githubusercontent.com/122301442/234367862-77d46342-cf69-4ad3-a50e-5088efaae884.mp4
CC: @yuisotozaki

15051 Updated local filing (CTCO) to respond to UX Observations

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/components/EntityInfo/EntityMenu.vue
src/views/Dashboard.vue

*Issue #:* none
- app version = 6.3.5
- added a missing getter

Added a missing getter

---

package-lock.json
package.json
src/components/common/Certify.vue
src/views/ConsentContinuationOut.vue

*Issue #:* /bcgov/entity#15051
- Yui's comment: https://github.com/bcgov/entity/issues/15051#issuecomment-1523874685
- Fixed allignment
- Fixed text colors
- Fixed validation trigger

15051 Second update to local filings to respond to UX observations

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/filings/ConsentContinuationOut.vue
src/components/Dashboard/FilingHistoryList/filings/StaffFiling.vue
src/services/date-utilities.ts
tests/unit/date-mixin.spec.ts

*Issue #:* bcgov/entity#16182
- app version = 6.3.9
- replaced some replace() with replaceAll()
- added a unit test

16182 Fixed some incomplete string replacements

---

package-lock.json
package.json
src/components/EntityInfo/EntityMenu.vue

*Issue #:* /bcgov/entity#16042
change "More actions" button style
Before (In DEV):
After:

16042 - Consent to Continue Out (change "More actions" button style)

---

package-lock.json
package.json
src/components/common/Directors.vue
tests/unit/FilingHistoryList2.spec.ts
tests/unit/LedgerConsentContinuationOut.spec.ts
tests/unit/allowable-actions-mixin.spec.ts

*Issue #:* bcgov/entity#16525
- app version = 6.5.1
- fixed feature flag mocking
- enabled tests
- fixed lint issue
- mocked console.warn in a test suite to hide expansion panel warnings

16525 Fixed unit test errors

---

package-lock.json
package.json
src/components/Dashboard/StaffNotation.vue
src/components/EntityInfo/EntityMenu.vue

*Issue #:* bcgov/entity#16562
- app version = 6.5.3
- added missing method to go to CCO filing

16562 Added missing method for CCO

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
tests/unit/TodoList2.spec.ts

*Issue #:* /bcgov/entity#16566
- app version = 6.5.5
- fixed Todo List logic for pending filings
- fixed Todo List logic for CCO
- updated unit test

16566 Fixed Todo List actions for pending (and CCO)

---

package-lock.json
package.json
src/components/common/ForeignJurisdiction.vue
src/components/common/index.ts
src/views/ConsentContinuationOut.vue
tests/unit/ForeignJurisdiction.spec.ts

*Issue #:* /bcgov/entity#16540
- Created the new Foreign Jurisdiction Component
- When country is not Canada or USA:
- When country is Canada or USA:

Created the Foreign Jurisdiction Component

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/filings/LimitedRestoration.vue

*Issue #:* /bcgov/entity#16376
- Ensure that the filing object is not pending before showing the item details. If it is pending use the default template.

16376 Fix pending limited restoration blurb

---

package-lock.json
package.json
src/interfaces/correction-filing-interface.ts
src/mixins/filing-mixin.ts
src/services/date-utilities.ts
src/views/ContinuationOut.vue
src/views/Correction.vue
tests/unit/DetailsList.spec.ts
tests/unit/DocumentsList.spec.ts
tests/unit/FilingHistoryList1.spec.ts
tests/unit/LegalObligation.spec.ts

*Issue #:* bcgov/entity#16763
- app version = 6.5.16
- set explicit correctedFilingDate type (ie, ISO date Pacific)
- fixed local correction correctedFilingDate format
- fixed Corrected Filing Date when building (draft) correction filing
- deleted a console.log left over from testing
- changed submittedDate in unit tests to GMT format

16763 fixed Corrected Filing Date format

---

package-lock.json
package.json
src/views/ConsentContinuationOut.vue

*Issue #:* /bcgov/entity#16761
Before:
After:

16761 Completing Party email address needs to be editable for end-user

---

package-lock.json
package.json
src/components/common/Certify.vue
src/components/common/DetailComment.vue
src/views/Correction.vue

*Issue #:* /bcgov/entity#16851
Made styling and functional changes based on the ones listed in the ticket here: https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/gh/bcgov/entity/16851

#16851 Filings UI: Styling issues in the correction module

---

package-lock.json
package.json
src/stores/filingHistoryListStore.ts
src/views/Correction.vue

*Issue #:* bcgov/entity#17108
- app version = 6.6.4
- fixed incorrect "current filing" assignment
- lint fix (automatic)

17108 fixed invalid variable

---

package-lock.json
package.json
src/components/common/DetailComment.vue
src/views/Correction.vue

*Issue #:* /bcgov/entity#16851
Fixed UI based on requirements

16851: Styling changes

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList.vue
src/components/Dashboard/FilingHistoryList/DetailsList.vue
src/components/Dashboard/FilingHistoryList/FilingTemplate.vue
src/components/Dashboard/FilingHistoryList/HeaderActions.vue
src/components/Dashboard/FilingHistoryList/subtitles/FiledAndPendingPaid.vue
src/components/Dashboard/FilingHistoryList/subtitles/FutureEffectivePaid.vue
src/components/Dashboard/StaffNotation.vue
src/components/Dashboard/TodoList.vue
src/components/dialogs/GenericErrorDialog.vue
src/interfaces/action-interface.ts
src/interfaces/index.ts

*Issue #:* /bcgov/entity#16364
Changed action store type to match new requirements

16364 Changed store actions type

---

package-lock.json
package.json
src/components/EntityInfo/EntityMenu.vue
tests/unit/EntityMenu.spec.ts

17317 - COOPS not in good standing should be able to file

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/HeaderActions.vue
tests/unit/FilingHistoryList1.spec.ts

*Issue #:* [/bcgov/entity17347
](https://github.com/bcgov/entity/issues/17347)

17347 - Enable correction on IA

---

.github/workflows/cd.yml
.github/workflows/ci.yml
Dockerfile
devops/cloudbuild-pr.yaml
package-lock.json
package.json
src/components/common/FileUploadPdf.vue
src/stores/configurationStore.ts
tests/unit/ConfigurationActions.spec.ts
tests/unit/SummaryDirectors.spec.ts
vite.config.js

*Issue #:* bcgov/entity#17592
- app version = 6.8.0
- updated Dockerfile
- changed vitest environment to jsdom
- updated CD script
- updated CI script
- updated PR script
- added error logging to FileUploadPdf.vue
- allowed use of env object in configuration store
- created env object for testing
- fixed obsolete "done()" in some tests

17592 Updates for Node 20

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue

*Issue #:17781* [/bcgov/entity17781](https://github.com/bcgov/entity/issues/17781)
set min width on the 'do not authorize' button.

17781 - set min width on the 'do not authorize' button.

---

src/components/common/DetailComment.vue
src/views/AgmLocationChg.vue
tests/unit/AgmLocationChg.spec.ts

- Updated Help Text
- Added the reason box with wiring
- Fixed validations
- Removed address component (to be replaced by another new one in a subsequent PR)
- Updated AGM Year rule
**Note: In order to help with reviewing and not create one huge PR, I'll be doing the work in multiple small PRs. I'm also merging to a new branch that I created. I will delete this branch immediately after the work is fully done.**
**I'll update the package version in my last PR.**

AGM Location Change First PR

---

package-lock.json
package.json
src/components/AgmLocationChange/AgmLocation.vue
src/components/AgmLocationChange/AgmYear.vue
src/components/common/DetailComment.vue

- Fixed error validations triggering although text-fields are valid.
Yui's comment: https://github.com/bcgov/entity/issues/18161#issuecomment-1792806349

18161 Updated in response to UXA notes

---

.github/workflows/cd.yml
package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/filings/ConsentContinuationOut.vue

*Issue #:* /bcgov/entity#16733
Added conditional statement for "FEDERAL"

16733 undefined placeholder for federal

---

package-lock.json
package.json
src/assets/styles/base.scss
src/components/AgmExtension/AgmExtensionEvaluation.vue
src/components/DigitalCredentials/dialogs/ReplaceCredentialErrorDialog.vue
src/components/common/VcardTemplate.vue
src/components/dialogs/ConfirmDissolutionDialog.vue
src/components/dialogs/NotEligibleExtensionDialog.vue
src/components/dialogs/index.ts
src/main.ts
src/mixins/allowable-actions-mixin.ts
src/utils/set-base-route-and-business-id.ts
src/views/AgmExtension.vue
src/views/AgmLocationChg.vue
tests/unit/AboutTheBusiness.spec.ts
tests/unit/AgmExtension.spec.ts
tests/unit/AgmExtensionEvaluation.spec.ts
tests/unit/AgmExtensionHelp.spec.ts
tests/unit/ConfigurationActions.spec.ts
tests/unit/ExtensionRequest.spec.ts
tests/unit/NotEligibleExtensionDialog.spec.ts

*Issue #:* bcgov/entity#18024
- app version = 7.0.3
- removed obsolete dialogs + code
- stopped watching changes to certify data
- cleaned up indentation
- added initial message box + CSS
- added NotEligibleExtension dialog
- removed waiveFees=true from AGM Extension
- removed waiveFees=true from AGM Location Chg
- added some unit test suites
- used allowable actions value from Legal API
- show alert on error starting app

18024 Incremental AGM Extension changes

---

package-lock.json
package.json
src/components/common/NameRequestInfo.vue

*Issue #:* /bcgov/entity#17917
Initialized empty strings for null firstNames and middleNames

17917 Added placeholder for null values

---

package-lock.json
package.json
src/components/AgmExtension/ExtensionRequest.vue
src/components/AgmLocationChange/AgmYear.vue
src/components/Dashboard/FilingHistoryList/filings/ConsentContinuationOut.vue
src/interfaces/agm-ext-eval-interface.ts
src/mixins/date-mixin.ts
src/services/date-utilities.ts
tests/unit/AboutTheBusiness.spec.ts
tests/unit/ExtensionRequest.spec.ts

*Issue #:* /bcgov/entity#18273
- Added the Logic for Scenario 1 for Extension Request component
[AGM Extensions Scenarios Final V1.0.docx](https://github.com/bcgov/business-filings-ui/files/13313693/AGM.Extensions.Scenarios.Final.V1.0.docx)

Extension Request Scenario 1

---

package-lock.json
package.json
src/components/AgmExtension/ExtensionRequest.vue
src/interfaces/agm-ext-eval-interface.ts
src/services/date-utilities.ts
src/views/AgmExtension.vue
tests/unit/AgmExtension.spec.ts
tests/unit/ExtensionRequest.spec.ts

*Issue #:* /bcgov/entity#18273
- Added the Logic for Scenario 1 for Extension Request component

18273 Extension Request Scenario 2

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/interfaces/api-task-interface.ts

*Issue #:* /bcgov/entity#18731
- Fixed the bug where AGM Extension wasn't showing in TODO List (in case payment failed)

18024 - Fixed AGM Extensions in TODO List

---

package-lock.json
package.json
src/components/AgmExtension/AboutTheBusiness.vue
src/components/AgmExtension/ExtensionRequest.vue
src/views/AgmExtension.vue

*Issue #:* /bcgov/entity#18273 and /bcgov/entity#18558
- Addresses UI comments from Yui (see tickets listed above for specifics)
- Fixed extension expiry minimum range
- Adjusted field labels and fields column width
- Adjusted spacing between radio menu options
- Adjusted AGM year field validation message
- Adjusted date picker validation triggering event. I will be implementing proper error messages in 18024

18273+18558 Update Extension Request component UI

---

package-lock.json
package.json
src/App.vue
tests/unit/App.spec.ts

*Issue #:* bcgov/entity#18736
- app version = 7.0.16a
- only fetch NR if this is a draft app (not filed app)
- updated display name to match usual IA filing
- deleted obsolete unit tests

18736 Fix error fetching NR after application is filed

---

package-lock.json
package.json
src/interfaces/business-state-interfaces.ts
src/mixins/allowable-actions-mixin.ts

*Issue #:* /bcgov/entity#18688
* gate digital business card based on Legal API allowable actions
* depends on: https://github.com/bcgov/lear/pull/2337

feat: digital credentials gate

---

package-lock.json
package.json
src/components/AgmExtension/ExtensionRequest.vue

*Issue #:* /bcgov/entity#18782

18782 fix error in wrong agm due date

---

package-lock.json
package.json
src/components/EntityInfo/EntityMenu.vue
src/views/AmalgamationSelection.vue
tests/unit/EntityMenu.spec.ts

*Issue #:* /bcgov/entity#18805
- Fixes in response to Yui's comment: https://github.com/bcgov/entity/issues/18805#issuecomment-1865014582

Updated Amalgamation Selection in response to UXA notes

---

package-lock.json
package.json
src/App.vue
src/interfaces/api-filing-interface.ts
src/interfaces/api-task-interface.ts
src/interfaces/todo-item-interface.ts
src/services/legal-services.ts

*Issue #:* bcgov/entity#16967
- app version = 7.0.32
- set missing draft app property
- updated some interface comments

16967 Set missing `displayLedger` property for draft apps

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/filings/AmalgamationFiling.vue
src/components/Dashboard/FilingHistoryList/filings/IncorporationApplication.vue
src/components/Dashboard/FilingHistoryList/filings/RegistrationFiling.vue

*Issue #:* bcgov/entity#19190
- app version = 7.0.33
- only show "return to MBR" for temp amalgamations
- only show "return to MBR" for temp incorporation applications
- only show "return to MBR" for temp registrations

19190 Fixed "return to MBR" issues

---

package-lock.json
package.json
src/enums/amalgamationEnums.ts
src/views/AmalgamationSelection.vue
tests/unit/AmalgamationSelection.spec.ts

*Issue #:* /bcgov/entity#19085
- create drafts for short form. Set required attributes
- redirect to Create UI
- update unit tests
Horizontal and vertical enabled:
Amalgamation draft created:
https://dev.create.business.bcregistry.gov.bc.ca/amalg-short-information?id=TvE9JH3WAI&accountid=3040

19085 - enable horizontal and vertical amalgamation launch

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/FilingTemplate.vue
tests/unit/AmalgamationFiling.spec.ts
tests/unit/App.spec.ts
tests/unit/EntityHeader.spec.ts
tests/unit/FilingHistoryList2.spec.ts
tests/unit/LedgerConsentContinuationOut.spec.ts
tests/unit/LedgerContinuationOut.spec.ts
tests/unit/TodoList1.spec.ts
tests/unit/filings.json

*Issue #:* /bcgov/entity#19038
Unit tests for short form amalgamations

19038 - unit tests for short form amalgamations

---

package-lock.json
package.json
src/views/AmalgamationSelection.vue

*Issue #:* /bcgov/entity#19039
Added the correctNameOption to the draft filing. 

Added correctNameOption to draft filing.

---

.env.example

*Issue #:* /bcgov/entity#19193
updated to use new gcp url

updated env file for legal name gcp

---

index.html
package-lock.json
package.json
src/App.vue
src/main.ts
src/services/enum-utilities.ts
tests/unit/App.spec.ts
vite.config.js

*Issue #:* bcgov/entity#19781
- app version = 7.0.42
- refactored aboutText into aboutApp and aboutSbc
- added special cases for displaying draft amalgamation task/filing name
- now display aboutApp in console
- updated filingTypeToName()
- deleted local font preload

19781 Updated draft amalgamation task/filing display name

---

package-lock.json
package.json
src/mixins/allowable-actions-mixin.ts
src/utils/feature-flags.ts
tests/unit/StaffNotation.spec.ts

*Issue #:* /bcgov/entity#19714
Added FF put back on

19714-ff-put-back-on

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/HeaderActions.vue
src/views/AmalgamationSelection.vue
tests/unit/FilingHistoryList1.spec.ts

*Issue #:* bcgov/entity#19823 and bcgov/entity#19843
- app version = 7.0.44
- added conditional disable for amalgamation correction
- redirect to Edit UI for amalgamation correction
- cleaned up AmalgamationSelection.vue
- pre-set numbered option for regular amalgamation draft
- updated (but did not fix) unit test

19823 and 19843 - added support for amalg correction + preset numbered option for reg amalg

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/filings/ConsentContinuationOut.vue
src/interfaces/api-filing-interface.ts

*Issue #:* bcgov/entity#19396
- app version = 7.1.1
- added check for valid expiry
- fixed API Filing IF (filings from API)

19396 Fixed consent for continuation out expiry bug

---

package-lock.json
package.json
src/components/Dashboard/Alerts.vue
src/components/Dashboard/Alerts/Amalgamation.vue
src/components/Dashboard/Alerts/FrozenInformation.vue
src/components/Dashboard/Alerts/MissingInformation.vue
src/components/Dashboard/Alerts/NotInCompliance.vue
src/components/Dashboard/Alerts/NotInGoodStanding.vue
src/stores/businessStore.ts
src/views/Dashboard.vue
tests/unit/Alerts.spec.ts
tests/unit/Amalgamation.spec.ts
tests/unit/Dashboard.spec.ts
tests/unit/NotInCompliance.spec.ts
tests/unit/NotInGoodStanding.spec.ts

*Issue #:* bcgov/entity#13881
- app version = 7.1.2
- created new Alerts component containing a single set of expansion panels
- refactored alert components to be a single expansion panel and use prop and emit
- moved some computeds to store
- cleaned up Dashboard.vue
- created new Alerts test suite
- cleaned up some test suites
- created NotInCompliance test suite

13881 Refactored alerts components

---

package-lock.json
package.json
src/components/Dashboard/Alerts.vue
src/components/Dashboard/Alerts/CorporateOnline.vue
src/components/EntityInfo/EntityMenu.vue
src/stores/businessStore.ts
tests/unit/Alerts.spec.ts
tests/unit/CorporateOnline.spec.ts
tests/unit/EntityHeader.spec.ts
tests/unit/EntityInfo.spec.ts
tests/unit/EntityMenu.spec.ts

*Issue #:* bcgov/entity#20397
- app version = 7.1.5
- added Corporate Online alert
- added/updated unit tests
- deleted unneeded router from EntityHeader test suite
- deleted unneeded router from Entity Menu test suite

20397 Added new alert

---

package-lock.json
package.json
src/App.vue
src/components/Dashboard/FilingHistoryList/filings/AmalgamationFiling.vue
src/components/Dashboard/FilingHistoryList/filings/IncorporationApplication.vue
src/components/Dashboard/FilingHistoryList/filings/RegistrationFiling.vue
src/services/legal-services.ts
src/stores/configurationStore.ts
src/stores/rootStore.ts
src/views/Dashboard.vue
tests/unit/AmalgamationFiling.spec.ts
tests/unit/App.spec.ts
tests/unit/Dashboard.spec.ts
tests/unit/IncorporationApplication.spec.ts
tests/unit/RegistrationFiling.spec.ts
tests/unit/legal-services.spec.ts

*Issue #:* bcgov/entity#20392
- app version = 7.1.8
- renamed "draft app" objects to "bootstrap filing"
- store bootstrap filing identifier
- updated Amalgamation filing component
- updated Incorporation Application filing component
- updated Registration filing component
- added a store getter

20392 Update completed IA/amalg/reg components

---

package-lock.json
package.json
src/components/AgmExtension/ExtensionRequest.vue
src/interfaces/agm-ext-eval-interface.ts
src/interfaces/api-filing-interface.ts
src/views/AgmExtension.vue
tests/unit/AgmExtension.spec.ts
tests/unit/ExtensionRequest.spec.ts

*Issue #:* bcgov/entity#20436
- app version = 7.1.10
- deleted Intended Date template
- updated validity code
- updated interfaces
- deleted field from filing
- update unit tests

20436 Removed Intended Date field

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/components/Dashboard/TodoList/PaymentPendingOnlineBanking.vue
src/stores/authenticationStore.ts
src/utils/navigate.ts
src/views/AmalgamationSelection.vue

*Issue #:* bcgov/entity#20818
- app version = 7.1.11
- created better getAccountId store getter and used it in place of old code
- don't save empty legalName in draft regular amalgamation
- don't save null correctNameOption in draft regular amalgamation
- improved email/phone logic

20818 Fixed draft amalgamation initial values

---

package-lock.json
package.json
src/interfaces/business-state-interfaces.ts
src/stores/businessStore.ts
tests/unit/EntityHeader.spec.ts

*Issue #:* /bcgov/entity#20932 & /bcgov/entity#20946
- Updated to use the new shared interface with updated fields
- Fixed getting "Unknown" in draft IAs when FF is on

20932 + 20946 legal name easy fix patches

---

package.json

- renamed script "serve" to "preview" to prevent confusion with other projects
- removed port specification so that it runs on a different port than "npm run dev" which should also prevent confusion

Renamed script to prevent confusion

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/HeaderActions.vue
tests/unit/ContinuationOut.spec.ts
tests/unit/FilingHistoryList1.spec.ts
tests/unit/FilingHistoryList2.spec.ts

*Issue #:* /bcgov/entity#21122
- Hided "Hide" button when details component is expanded

21122 - Hide documents button for IAs

---

package-lock.json
package.json
src/components/Dashboard/Alerts/CorporateOnline.vue
src/components/Dashboard/TodoList.vue

*Issue #:* bcgov/entity#21028
- app version = 7.2.8
- disabled AR todo item is COLIN FF is disabled
- deleted an unused getter

21028 Disabled AR todo item for non-BEN corps

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue
src/components/Dashboard/TodoList/PaymentPaid.vue
src/interfaces/todo-item-interface.ts

*Issue #:* bcgov/entity#21194
- app version = 7.2.14
- added pending filing sub-title when payment is completed
- do not show actions when filing is pending but payment is completed
- show PaymentPaid sub-component when payment is completed
- added contact info to PaymentPaid sub-component
---
before
after

21194 Added handling for pending filing with completed payment

---

package-lock.json
package.json
src/services/enum-utilities.ts
tests/unit/EntityHeader.spec.ts
tests/unit/enum-utilities.spec.ts

*Issue #:* /bcgov/entity#21771
- Changed the dissolution reason for involuntary dissolution

21771 - Changed Involuntary Dissolution Reason

---

package-lock.json
package.json
src/stores/filingHistoryListStore.ts
tests/unit/FilingHistoryList1.spec.ts

*Issue #:* bcgov/entity#21779
- app version = 7.3.4
- clear current panel so other tests re-open it

21779 Fixed unit tests

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/filings/ContinuationIn.vue
src/components/Dashboard/TodoList.vue
tests/unit/ContinuationIn.spec.ts

*Issue #:* bcgov/entity#22399
- app version = 7.3.17
- italicized latest review comment in Todo List
- italicized latest review comment in Filing History List
- added unit tests

22399 Added unit tests

---

package-lock.json
package.json
src/components/Dashboard/Alerts/InDissolution.vue
src/mixins/date-mixin.ts
tests/unit/InDissolution.spec.ts

*Issue #:* /bcgov/entity#22434
- Updated in dissolution alert
- Updated unit tests
*Local Testing*

22434 Update in dissolution alert

---

package-lock.json
package.json
src/components/Dashboard/FilingHistoryList/filings/ContinuationIn.vue
src/components/Dashboard/PendingList/PendingTemplate.vue
src/components/Dashboard/PendingList/filings/ContinuationIn.vue
src/components/Dashboard/TodoList.vue
src/views/Dashboard.vue
tests/unit/ContinuationIn.spec.ts

*Issue #:* /bcgov/entity#23520
- Handle CHANGE_REQUESTED status: reason in gray block; change wording; show NR expiry
- Handle APPROVED status: show NR expiry, authorization expiry, split button to delete
- Handle NR approved draft status: change button label, show NR expiry
- RESUBMITTED & AWAITING_REVIEW are handled already, updated wording
- REJECTED & APPROVED application are handled already

23520 - Handle Continuation Draft States

---

package-lock.json
package.json
src/components/Dashboard/TodoList.vue

*Issue #:* /bcgov/entity#23967
- Removed spinner for approved continuation in drafts

23967 Removed spinner for approved continuation in drafts

---

package-lock.json
package.json
src/components/NoticeOfWithdrawal/StaffPayment.vue
src/routes.ts
src/views/NoticeOfWithdrawal.vue

*Issue #:* /bcgov/entity#25082
- minor UX fixes (see ticket for requested changes)

25082-Notice of Withdrawal UX Fixes

---

package-lock.json
package.json
src/components/NoticeOfWithdrawal/RecordToBeWithdrawn.vue
src/views/NoticeOfWithdrawal.vue

*Issue #:* /bcgov/entity#25579
- Remove the "Save" and "Save and Resume Later" button in NoW filing
- Add a warning when click Cancel button and there are changes made
- Remove unneeded codes for save/load draft

25579 - Remove Save/Resume Button for NoW filing

---

package-lock.json
package.json

*Issue #:* bcgov/entity#26211
- app version = 7.4.22
- changed sbc-common-components to version without SBC Connect changes

26211 changed sbc-common-components to version without SBC Connect changes

---

package-lock.json
package.json

*Issue #:* bcgov/entity#26351
- app version = 7.4.19a
- imported latest BaseAddress component

26351 imported latest BaseAddress component

---

package-lock.json
package.json

*Issue #:* bcgov/entity#36251
- app version = 7.4.19a
- imported latest BaseAddress component

26351 imported latest BaseAddress component (#727)

---

package-lock.json
package.json
src/axios-auth.ts
vite.config.js

*Issue #:* bcgov/entity#26471
- app version = 7.4.27
- updated app name
- added app name to Vite config
- simplified Vite config
- added App Name to Axios requests

26471 added App-Name to request headers

---

package-lock.json
package.json
src/components/common/Directors.vue
src/components/common/SummaryDirectors.vue

*Issue #:* /bcgov/entity#27069

27069 disable_ceased_director_address_text

---

package-lock.json
package.json
src/views/CourtOrder.vue

*Issue #:* /bcgov/entity#27335
- Fix the bug the first section is not validated

27335 - Fix Validation Section Bug in Court Order Filing

---

package-lock.json
package.json
src/components/common/OfficeAddresses.vue
src/mixins/common-mixin.ts
src/views/StandaloneOfficeAddressFiling.vue

*Issue #:* /bcgov/entity#27042

27042 remove address fetch error

---

package-lock.json
package.json
src/components/DigitalCredentials/CredentialsStepper.vue
src/components/DigitalCredentials/CredentialsWebSocket.vue
src/components/DigitalCredentials/dialogs/ConfirmPreconditionDialog.vue
src/interfaces/business-state-interfaces.ts
src/interfaces/digitalCredentials-interface.ts
src/mixins/allowable-actions-mixin.ts
src/services/legal-services.ts

*Issue #:* https://github.com/bcgov/entity/issues/27331
~DO NOT MERGE UNTIL LEGAL API PRs ARE MERGED~ _those are now merged!_

27331 feat: DBC2

---

package-lock.json
package.json
src/components/common/OfficeAddresses.vue

*Issue #:* /bcgov/entity#27042

27042_hotfix save button issue

---

package-lock.json
package.json
src/components/EntityInfo/EntityHeader.vue
src/interfaces/api-filing-interface.ts
src/stores/filingHistoryListStore.ts

*Issue #:* /bcgov/entity#27411
- Add the AUTHORIZED TO AMALGAMATE OUT badge in filing UI

27411 - Authorized to Amalgamate Out Badge

---

package-lock.json
package.json
src/components/DigitalCredentials/CredentialsInfo.vue

*Issue #:* [/bcgov/entity#27331](https://github.com/bcgov/entity/issues/27331)
- Minor tweak to on-screen text on the Digital Business Card page to match designs
Existing:
Change:
Link goes to https://vancouver.ca/doing-business/get-a-business-licence.aspx

27331 "Where to use your Business Card" text update

---

package-lock.json
package.json
src/mixins/breadcrumb-mixin.ts
src/views/Default.vue

*Issue #:* /bcgov/entity/27186
1.) Update to breadcrumb business crumb so it uses proper dashboard url.
2.) Update to routes redirect so it redirects to proper dashboard url.

27186 breadcrumb and routing fix when redirecting to dashboard

---

package-lock.json
package.json
src/components/DigitalCredentials/CredentialsTermsOfUse.vue

*Issue #:* /bcgov/entity#29495
Just edit the TOU text in the Vue component. See linked ticket for details on changes.

29495 Update DBC Terms Of Use

---

package-lock.json
package.json
src/components/common/Directors.vue
src/stores/businessStore.ts
tests/unit/Directors.spec.ts

*Issue #:* /bcgov/entity#28814
- Add legal name change checkbox and validation
- Add URL link to form based on the Business Type (as per Mihai, we are not implementing the Extraprovincial case yet)
- Update + Add unit tests
_****Note: "formerly" piece that can be seen in the designs is out of scope at this time as we are still waiting for a response from Business**_
**[Default case:](https://www.figma.com/design/Gsp0M1gpYL1uQq3BttYras/Director-Change?node-id=2001-7&m=dev&focus-id=16385-24573)**
[**Regular Case:**](https://www.figma.com/design/Gsp0M1gpYL1uQq3BttYras/Director-Change?node-id=16383-4489&t=5jVS5xKO1Ck6Hzla-0)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the …

288144 - Add Legal Name Checkbox to COD Filing

---

devops/cloudbuild-pr.yaml

Update CloudBuild Image

---

package-lock.json
package.json
src/App.vue
src/services/legal-services.ts

*Issue #:* /bcgov/entity#30248

30248 update API error parsing

---

.env.example
devops/vaults.env
package-lock.json
package.json
src/App.vue
src/interfaces/configuration-state-interface.ts
src/mixins/breadcrumb-mixin.ts
src/stores/configurationStore.ts
tests/unit/ConfigurationActions.spec.ts

*Issue #:* bcgov/entity#30238
- deleted obsolete key VUE_APP_BUSINESSES_URL
- app version = 8.0.13
- fixed dialog exit to BRD URL
- fixed MBR breadcrumb URL
- fixed staff dashboard breadcrumb URL

30238 cleaned up some env keys and fixed breadcrumbs
