src/components/Dashboard/TodoList.vue, tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#2647
Changed button text from File Now to File Annual Report.
Duplication of Richard's changes.
=> Changed button text from File Now to File Annual Report

src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/TodoList.vue, src/store/getters.ts, src/views/AnnualReport.vue, src/views/Correction.vue, src/views/StandaloneDirectorsFiling.vue, src/views/StandaloneOfficeAddressFiling.vue, tests/unit/AnnualReport.spec.ts
This is Part 3 of the the Correction Filing task, which includes:
- implemented loading draft correction
- renamed some route params to correctedFilingId
- blocked correcting a correction (for now)
- enabled Save for corrections
- changed Save buttons to always be enabled (in all filings, per Scott)
- changed some strings to Filing Types
- added some explicit types
Part 4 will implement:
- updates to unit tests
=> correction filing (part 3)

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/TodoList.vue, src/interfaces/filingData-interfaces.ts, src/mixins/common-mixin.ts, src/mixins/entityFilter-mixin.ts, src/mixins/filing-mixin.ts, src/mixins/index.ts, src/mixins/resource-lookup-mixin.ts, src/store/actions.ts, src/store/mutations.ts, src/store/state.ts, src/views/AnnualReport.vue, src/views/Correction.vue, src/views/StandaloneDirectorsFiling.vue, src/views/StandaloneOfficeAddressFiling.vue
This is Part 4 of the Correction Filing task, which inclues:
- moved some methods to Filing Mixin
- moved Filing Data to global store
- init Filing Data on filing creation
- expanded use of types
- updated version number
Part 5 will implement:
- updates to Summary Staff Filing component
- updates to unit tests
=> correction filing (part 4)

src/views/Correction.vue
- fixed Certified By always reverting to original filing
=> correction filing (fixed Certified By bug)

src/components/EntityInfo.vue
This was likely broken by the recent "@mdi/font" package upgrade. (Other icons were also obsoleted but have been fixed.) So this is a simple change to use the new icon name.
=> replaced obsolete Material Design Icon

src/main.ts
*Issue #:* /bcgov/entity#2949
- new UI expects Business ID in route, but users probably don't have new URL bookmarked yet
- we want to handle this as gracefully as possible
- the new behaviour looks like the previous behaviour
=> removed alert on startup error + redirect to "Cooperatives Online"

src/components/common/Directors.vue, tests/unit/Directors.spec.ts
*Issue #:* /bcgov/entity#1613
* Implemented director name change reset btn.
* Fixed the cancel btn functionality.
* Updated unit testing.
=> Director Name Change Reset

src/components/common/Directors.vue
*Issue #:* /bcgov/entity#
* Fixes a small bug where a directors name could be overwrote when cancelling an address change. 
=> Small Fix for Cancelling Address Changes

src/App.vue, src/axios-auth.ts, src/router.ts
*Issue #:* /bcgov/entity#3620
- added logic to catch error for token refresher failure and refresh the page ( an error is thrown if the refresh token has expired)
=> 3620 - add clear keycloak session logic on token refresh initialization failure

src/components/Dashboard/TodoList.vue, src/components/dialogs/BcolErrorDialog.vue, src/views/AnnualReport.vue, src/views/StandaloneDirectorsFiling.vue, src/views/StandaloneOfficeAddressFiling.vue, tests/unit/AnnualReport.spec.ts, tests/unit/BcolErrorDialog.spec.ts, tests/unit/StandaloneDirectorsFiling.spec.ts, tests/unit/StandaloneOfficeAddressFiling.spec.ts, tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#3713
Payments that have completed should not result in a redirect. This goes for free filing changes as well as BCONLINE. The payment status is now propogated to the front end and is stored with the filing for any other future wizardry that needs to occur. This is a fairly minor change
P.S - Hopefully no lint errors...I did run linting
=> change paymentErrorCode to paymentStatusCode

src/App.vue, src/components/Dashboard/CompleteFiling.vue, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/PendingFiling.vue, src/components/EntityInfo.vue, src/enums/entityStatus.ts, src/views/Dashboard.vue, tests/unit/App.spec.ts, tests/unit/CompleteFiling.spec.ts, tests/unit/Dashboard.spec.ts, tests/unit/EntityInfo.spec.ts, tests/unit/PendingFiling.spec.ts
*Issue #:* /bcgov/entity#3955
- update initialization check to allow COMPLETED state
- changed EntityStatus.PAID_INCORP_APP to EntityStatus.FILED_INCORP_APP
- added component for complete filing (used only for completed IA with temp reg num)
- removed has-blocker-filing event from FilingHistoryList as an IA filing will show up when complete and using the real business identifier which will disable changes(we don't want this). This check has been changed to always disable changes if it we are using a temp reg num (check is in dashboard component) and any pending states in the history filings are already checked in the dashboard component as well.
- removed hasBlockerFiling code from Dashboard component
- update pending filing with return to dashboard button
- …
=> 3955 - handling temporary IA complete state

src/components/Dashboard/TodoList.vue, src/components/dialogs/ConfirmDialog.vue
*Issue #:* /bcgov/entity#4040
- updated delete Incorporation Application logic so the doDeleteDraft() function allows for NOT triggering a dashboard reload as this causes an IA to be re-evaluated briefly showing an error message when the redirect is slow.
=> 4040 - delete draft IA updates

src/common/FeatureFlags.ts, src/components/Dashboard/TodoList.vue, src/views/Dashboard.vue
… for bcomp
*Issue #:* /bcgov/entity#4124
Added a new feature flag that determines the availability of maintenance filing for BComp
Changes in dashboard and Todo list to show different content based on feature flag
Note : If you want to test this locally you can use the ld client id from the dev config map in the local configuration or change the default value of the flag to false in the FeatureFlag.ts file
=> Using Feature flags to control the availability of maintenance filing for BComp

src/App.vue, tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#4144
Added a filter to set only the directors to the store incase of an incorporation application
Updated a test that was using incorrect json as the parties data
=> Bug fix - Blank record in the director list if incorporator is an org

src/components/Dashboard/TodoList.vue, tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#3341
* Fixes bug where 'Enable' checkbox for the BComp Annual Reports wasn't disabled when there was a Change of Address filing pending.
* Adds unit test.
=> Bug fix when COA pending

src/components/StandaloneDirectorChange/CODDate.vue, tests/unit/CODDate.spec.ts
*Issue #:* /bcgov/entity#4219
Added the logic to exclude AR date for BCOMP
Updated Tests
=> COD date changes for BCOMP

src/components/Dashboard/TodoList.vue, tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#4354
* Bux fix where filings UI was updating the parent before the tasks/filings were loaded.
* Added a watcher on the taskItems and updates the parent (Dashboard) when changes occur in the taskItems array.
=> Filings UI Bug Fix - Watcher to handle Emit

src/components/Dashboard/AddressListSm.vue, src/components/Dashboard/DirectorListSm.vue
*Issue #:* /bcgov/entity#4653
- removed extra padding below office addresses mailing address
- added extra padding below current directors delivery address
=> fixed padding in dashboard office addresses and current directors

src/views/AnnualReport.vue
Because the annualReportDate is a date field ( not a datetime field), we should be passing what the user selected in the date component. The UTC issue matters only for datetime fields like effective_date
=> Fix for annual report filings failing in prod

src/components/Dashboard/FilingHistoryList.vue, src/enums/filingNames.ts, src/enums/filingTypes.ts, src/mixins/enum-mixin.ts, tests/unit/FilingHistoryList.spec.ts
*Issue #:* /bcgov/entity#5183
Added code for loading transition filing ( See a lot of duplicate code for loading each type of filing. May need a clean up at some point of time)
Updated enums and mixins needed for handling a new filing type in the history list
Updated tests
The screenshot of the transition filing in the history list has been shared with Scott and he approved it
=> Display Transition Filing in the filing history list

src/App.vue
*Description of changes:* When retrying to load app after error (eg, due to KC timeout), force-restart token service (which may force an app reload and subsequent re-login). This will succeed in more situations than just retrying the fetches without a new token.
=> improved app retry handler

src/components/common/Directors.vue
*Issue #:* /bcgov/entity#5622
- reset empty officer after pushing new director data
=> fix for empty officer.middleInitial

src/App.vue
When retrying to load app after an auth error, clear the current KC session and hard-reload the page to try again; otherwise try to fetch the data again. The previous solution (#161) typically caused 2 error dialogs and app reloads. This solution is more heavy-handed and causes just 1.
=> improved app retry handler, take 2

.gitignore, package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/enums/effectOfOrderTypes.ts, src/enums/index.ts, src/interfaces/index.ts, src/mixins/enum-mixin.ts, vue.config.js
Issue #: /bcgov/entity#6650
Description of changes:
- Updated package number to 3.8.6
- Updated package.json to use v1.0.17 of bcrs-shared-components/interfaces.  Contains court order related interface updates
- Updated FilingHistoryList.vue component to use court order interface and to properly populate data from BE into history item object
- Created EffectOfOrderTypes enum and added helper methods to enum mixin
- Updated proxy config in vue.config.js as was having issues grabbing keycloak.json locally
Note: existing test already tested the updated fields so no updates were made to tests.
=> 6650 update alterations ledger to include court of order fields

package-lock.json, package.json, src/assets/styles/base.scss, src/components/Dashboard/FilingHistoryList.vue, src/enums/filingTypes.ts, src/interfaces/filing-interface.ts, src/interfaces/historyItem-interface.ts, tests/unit/FilingHistoryList.spec.ts
*Issue #:* /bcgov/entity#4389
- Updated the filing history to include the new "registrar's notation" ledger item
- Updated the filing history to include the new "registrar's order" ledger item
- Updated the filing history to include the new "Court order" ledger item
- These ledger items cannot be corrected
- Detail comments enabled.
- Updated unit tests
*NOTES:*
* This was done off these UXpins, currently all we have: https://preview.uxpin.com/1f3b95dd1c4122ddb79c854e9498f5e8073cbfa1#/pages/130733104/simulate/no-panels
* Also done off the current schema, since these filings don't exist and needed to be mocked out. Schema is subject to change but this won't impact the Filings History List unless the title and/or FilingType changes. I'm assuming that won't.
By …
=> History List Handling for Staff Filings

src/App.vue
At the moment, it is not possible to test a CP IA, because the Entity Dashboard (this project) rejects the `filing.business.legalType` of "CP". This PR adds COOP as a support business legal type.
=> Added CP as a supported business legal type

package-lock.json, package.json, src/interfaces/dissolution-filing-interface.ts, src/mixins/filing-mixin.ts, src/store/getters.ts
*Issue #:* /bcgov/entity#8913
* Add getter for business founding date (`getEntityFoundingDate`)
* Add `foundingDate` to `business` block of initial draft filing for dissolutions.  This is required as it is used in special resolution date validation logic for Coop voluntary dissolutions.
=> 8913 Add founding date to dissolution filing business block

package-lock.json, package.json, src/components/StandaloneDirectorChange/CODDate.vue, tests/unit/CODDate.spec.ts
*Issue #:* /bcgov/entity#10319
Note: the _actual_ fix for this bug is [10159](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/10159).
- removed formatting for min and max date in error message
- app version: 4.1.1
=> 10319 Removed formatting for min and max date in error message

src/views/Dashboard.vue
- removed extra 2.25rem whitespace at the top of the dashboard
Screenshot:
=> Updated Dashboard.vue

package-lock.json, package.json, src/App.vue, src/components/Dashboard/FilingHistoryList/PendingFiling.vue, src/components/EntityInfo.vue, tests/unit/EntityInfo.spec.ts, tests/unit/PendingFiling.spec.ts
*Issue #:* /bcgov/entity#10619 & /bcgov/entity#10150
* Connects Download business summary btn to request for document
* Adds unit tests for btn
* Relocate summary btn to present for all business states (other than Temp Reg), ie active & historical
* Remove the 'Goto Dashboard' Btn and functionality from the pending filing in the filing history list
=> Connect Business Summary

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, tests/unit/FilingHistoryList.spec.ts
*Issue #:* /bcgov/entity#10934
- Updated the filing history list component to show the view documents button only if documentsLink exists and has a non null value
- Updated tests
=> Hide Show Documents Button in the Filing History for filing with no documents

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue
*Issue #:* /bcgov/entity#11202
The data section is available in the filings json only for a completed filing. Added a check for that
=> Filing UI not displaying FED alteration

package-lock.json, package.json, src/components/dialogs/PaymentErrorDialog.vue, tests/unit/PaymentErrorDialog.spec.ts
Issue #: [/bcgov/entity#9014](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/9014)
Description of changes:
When a payment error occurred, a popup window for "Unable to process payment" show up.
tags are included in the text in the popup window, and they need to be removed.
=> 9014 HTML tags show up in the warning popup window

package-lock.json, package.json, src/components/Dashboard/FirmsAddressList.vue, src/components/Dashboard/ProprietorPartnersListSm.vue, tests/unit/AddressListSm.spec.ts, tests/unit/FirmsAddressList.spec.ts, tests/unit/ProprietorPartnersListSm.spec.ts
*Issue #:* [/bcgov/entity#12024](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12024)
When a user opens their entity dashboard for an SP/GP, if data is missing we need to:
- When the field would normally not be empty for this entity type
- This applies to firms only (so only those components need this change)
=> 12024 Filings UI - Display "Not Entered" for missing data on address and prop/part components

package-lock.json, package.json, src/components/Dashboard/FirmsAddressList.vue, src/components/Dashboard/ProprietorPartnersListSm.vue, src/components/Dashboard/StaffNotation.vue, src/components/dialogs/AddStaffNotationDialog.vue, tests/unit/AddressListSm.spec.ts, tests/unit/FirmsAddressList.spec.ts, tests/unit/ProprietorPartnersListSm.spec.ts, tests/unit/StaffNotation.spec.ts
*Issue #:* [/bcgov/entity#11886](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/11886)
**Completed Tasks:**
- Redirect path related to ticket #111894. 
- Suggested url is "/conversion". 
- Edit UI is related to ticket #111894. 
- `filing.displayName` must be "Record Conversion Filing" (related ticket #11771?)
**Additional change:**
=> 11886 FILINGS UI - Start Record Conversion (Add filing to list of staff filings)

package-lock.json, package.json, src/App.vue, src/components/Dashboard/FirmsAddressList.vue, src/components/Dashboard/ProprietorPartnersListSm.vue, tests/unit/FirmsAddressList.spec.ts
*Issue #:* /bcgov/entity#12024
**Completed UXA Observations:**
**404 Handler**
**New Ticket**
=> 12024 Fix Filings UI - Display "Not Entered" for missing data on address and prop/part components

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/CompletedDissolution.vue, src/resources/BreadcrumbResources.ts, src/utils/fetch-config.ts, src/utils/navigate.ts, tests/unit/AnnualReport.spec.ts, tests/unit/App.spec.ts, tests/unit/EntityInfo.spec.ts, tests/unit/FilingHistoryList.spec.ts, tests/unit/StandaloneDirectorsFiling.spec.ts, tests/unit/StandaloneOfficeAddressFiling.spec.ts, tests/unit/TodoList.spec.ts, tests/unit/allowable-actions-mixin.spec.ts, tests/unit/fetch-config.spec.ts
*Issue #:* [/bcgov/entity#11374](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/11374)
- removed `accountId` in file: fetch-config.ts 
- updated `accountId` in file: navigate.ts
- updated app version in file: package.json
- updated many unit test files to accommodate `CURRENT_ACCOUNT`
=> 11374 Filings UI: get account id from CURRENT_ACCOUNT

package-lock.json, package.json, src/components/dialogs/AddStaffNotationDialog.vue
*Issue #:* /bcgov/entity#12092
* remove frontend validation for court order number (not a required field)
* update data sent for admin dissolution in court order object
=> remove court order validation for AD and PutBackOn

package-lock.json, package.json, src/interfaces/correction-filing-interface.ts, src/mixins/filing-mixin.ts
*Issue #:* /bcgov/entity#13197
- don't save Certified By in BEN or FM draft correction
- app version = 5.2.18
=> 13197 Don't save Certified By in a draft correction

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/TodoList.vue, src/components/dialogs/FileCorrectionDialog.vue, src/components/dialogs/index.ts, src/enums/correctionTypes.ts, src/enums/index.ts, src/interfaces/correction-filing-interface.ts, src/interfaces/todo-item-interface.ts, src/mixins/enum-mixin.ts, src/mixins/filing-mixin.ts, src/views/Correction.vue, tests/unit/Correction.spec.ts, tests/unit/FilingHistoryList.spec.ts
*Issue #:* /bcgov/entity#12392
=> 12392 Correction Filing Dialog for Firm Corrections

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, tests/unit/FilingHistoryList.spec.ts
*Issue #:* bcgov/entity#13320
- allow corrections to corrected filings
- allow corrections to BEN IAs
- allow corrections to corrections
- app version = 5.3.0
=> 13320 Allow correction to a corrected or correction filing

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/interfaces/correction-filing-interface.ts, src/mixins/filing-mixin.ts
*Issue #:* bcgov/entity#13347
- no longer fetch corrected filing
- no longer attach corrected filing to correction
- deleted obsolete comments
- updated Correction Filing interface
- combined/updated correction build methods
- app version = 5.3.1
=> 13347 Stop attaching corrected filing to draft corrections

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue
*Issue #:* /bcgov/entity#12671
- add gavel icon for court order title in the filing list
- Requested UI change on this PR bcgov/business-filings-ui/pull/393
=> 12671 Add missing gavel to Court order filings in list

package-lock.json, package.json, src/components/Dashboard/Alerts/MissingInformation.vue, src/components/common/ContactInfo.vue, src/utils/feature-flags.ts, tests/unit/MissingInformation.spec.ts
*Issue #:* bcgov/entity#13953
- added ability to hide Contact Info phone numbers
- added logic to hide phone numbers in Missing Information alert
- added feature flag to enable logic
- app version = 5.7.11
=> 13953 Conditionally hide alert phone numbers

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/TodoList.vue, tests/unit/FilingHistoryList1.spec.ts
*Issue #:* bcgov/entity#14159
- updated correctThisFiling() to handle other filing types
- updated disableCorrection() to handle other filing types
- updated doResumeFiling() to handle other filing types
- refactored disableCorrection() to better line up with unit test
- updated unit test
- app version = 5.7.15
=> 14159 Allow corrections to correction and conversion filings

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/TodoList.vue, tests/unit/FilingHistoryList1.spec.ts, tests/unit/allowable-actions-mixin.spec.ts
*Issue #:* bcgov/entity#14159
- disabled Conversion corrections
- un-disabled Transition corrections (now falls into "others enabled by default")
- app version = 5.7.16
=> 14159 Disabled conversion corrections + cleanup

package-lock.json, package.json, src/components/AnnualReport/ARDate.vue, src/components/Dashboard/AddressListSm.vue, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/StaffNotation.vue, src/components/Dashboard/TodoList.vue, src/components/StandaloneDirectorChange/CODDate.vue, src/components/common/Directors.vue, src/components/common/OfficeAddresses.vue, src/components/common/SummaryDirectors.vue, src/interfaces/history-item-interface.ts, src/mixins/allowable-actions-mixin.ts, src/mixins/resource-lookup-mixin.ts, src/store/getters.ts, src/views/AnnualReport.vue, src/views/Correction.vue, src/views/Dashboard.vue, src/views/StandaloneDirectorsFiling.vue, src/views/StandaloneOfficeAddressFiling.vue, tests/unit/FilingHistoryList2.spec.ts
*Issue #:* bcgov/entity#14306 + bcgov/entity#14322 + bcgov/entity#14343
- replaced most isBComp with isBenBcCccUlc to extend functionality to new entity types
- renamed isFutureEffectiveBcompCoaPending -> isFutureEffectiveCoaPending
- show AR checkbox for new entity types
- added method to simplify template logic
- updated method to disable File button for new entity types
- added isBenBcCccUlc getter
- app version = 5.7.20
- added missing todo item field for a resumed BEN/BC/CCC/ULC annual report
=> 14306 Extend BComp logic to BC/CCC/ULC (Annual Report, etc)

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/TodoList.vue
*Issue #:* /bcgov/entity#14530
- App version -> 5.7.25
- Alteration corrections redirect to edit ui
=> 14350 Redirect alteration corrections to the Edit UI instead of handling locally

package-lock.json, package.json, src/components/Dashboard/StaffNotation.vue
Issue #: /bcgov/entity#14965
Description of changes:
Fixed the ability to file register notation for sp/gp filling
=> 14965 Fixed register notation disabled for SP/GP filling

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/FilingHistoryList/LimitedRestorationFiling.vue, src/interfaces/history-item-interface.ts, src/mixins/enum-mixin.ts, tests/unit/FilingHistoryList1.spec.ts
*Issue #:* /bcgov/entity#14808
Add limited restoration component to the dashboard's filing history.  Confirm that full restoration display correctly.
=> 14808 - show full and limited restorations

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/FilingHistoryList/StaffFiling.vue, src/components/Dashboard/StaffNotation.vue, src/components/Dashboard/TodoList.vue, src/enums/filingCodes.ts, src/enums/filingNames.ts, src/enums/filingTypes.ts, src/enums/restorationTypes.ts, src/enums/routes.ts, src/interfaces/api-filing-interface.ts, src/interfaces/api-task-interface.ts, src/interfaces/history-item-interface.ts, src/interfaces/index.ts, src/interfaces/todo-item-interface.ts, src/mixins/enum-mixin.ts, src/routes.ts, src/views/AnnualReport.vue, src/views/ConsentContinuationOut.vue, src/views/StandaloneDirectorsFiling.vue, src/views/StandaloneOfficeAddressFiling.vue, tests/unit/FilingHistoryList1.spec.ts, tests/unit/FilingHistoryList2.spec.ts, tests/unit/StaffFiling.spec.ts, tests/unit/TodoList2.spec.ts, tests/unit/enum-mixin.spec.ts, tests/unit/filings.json
*Issue #:* bcgov/entity#15042
- added new route
- added new enum mixin method
- added item to staff notation list + route to new page
- updated Filing History List to support new filing
- updated Todo List to support new filing (staff and non-staff)
- removed unused "haveData" from some filings
- added filing code
- added filing name
- added filing type
- added route name
- added initial Consent Continuation Out page
- deleted obsolete "changeOfName" object
- added "consentContinuationOut" object
- added properties to HistoryItemIF
- cleaned up staff filing code
- added handling for Consent to Continuation Out filings
- misc cleanup
- app version = 5.10.0
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> 15042 Added Consent to Continuation Out to dashboard

package-lock.json, package.json, src/store/Configuration/mutations.ts, tests/unit/Configuration.spec.ts
*Issue #:* DEV fix
The SBC Header uses session variables to determine the AUTH_WEB_URL and other URL paths.  This PR adds back the session variables that were removed in the previous commit.
=> add back session variables for SBC Header

package-lock.json, package.json, src/components/Dashboard/StaffNotation.vue, tests/unit/StaffNotation.spec.ts
*Issue #:* /bcgov/entity#15092
In edit-ui, we're overloading the restoration endpoint and reusing it for ~~full restorations,~~ limited-to-full restorations and limited-extension restorations.  By separating restorations to different ~~endpoints~~ routes (thanks Sev!), we can keep the code in edit-ui cleaner and easier to read.  
=> 15092 - separate restoration endpoints in edit-ui

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/FilingTemplate.vue, src/components/Dashboard/FilingHistoryList/filings/StaffFiling.vue
*Issue #:* bcgov/entity#15692
- app version = 6.2.1
- cleaned up whitespace in Filing Template default body
- cleaned up whitespace in Staff Filing body
(I hacked the code to use this template instead of the Staff Filing template)
(normal view for this Court Order filing)
=> 15692 Cleaned up some whitespace

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/HeaderActions.vue, src/components/Dashboard/TodoList.vue, tests/unit/TodoList1.spec.ts
*Issue #:* bcgov/entity#15892 & bcgov/entity#15893
- Open File Correction dialog when filing a correction for Director & Address change
- Redirect to Edit UI
- Save and resume redirects to Edit UI also
- The ability to correct is dependent on `supported-correction-entities` feature flag. If entity is not supported in a specific environment, the "File a Correction" button will be disabled.
For reference:
https://user-images.githubusercontent.com/122301442/233743788-a1a235ee-b5e3-411f-8c4b-5effd03fdb88.mp4
=> 15892 Director & Address change correction

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/filings/ConsentContinuationOut.vue, src/components/Dashboard/FilingHistoryList/filings/StaffFiling.vue, src/store/actions.ts, src/views/ConsentContinuationOut.vue, tests/unit/ConsentContinuationOut.spec.ts, tests/unit/StoreActions.spec.ts
*Issue #:* bcgov/entity#16182
Commit 1:
- app version = 6.3.8
- get order details from correct filing object (in consent)
- display newlines in order details (consents and staff filings)
- fixed store action fetching null filing
- fixed some lint errors (maxlen)
- fixed broken consent tests
- fixed broken actions tests
Commit 2:
- now restore hasPlanOfArrangement flag from effectOfOrder property
- now save effectOfOrder property depending on hasPlanOfArrangement flag
=> 16182 Fixed null filing fetch error + fixed Consent orderDetails and effectOfOrder

package-lock.json, package.json, src/axios-auth.ts
*Issue #:* [/bcgov/entity15241](https://github.com/bcgov/entity/issues/15241)
Axios defaults to sending an `Authorization` header for any request it makes - newer version of Minio does not like this header, and throws 400 errors. This change will not auto-add the header for urls with `minio` in them.
=> 15241 minio upgrade fix

package-lock.json, package.json, src/components/Dashboard/StaffNotation.vue
- app version = 6.3.10
- hide "Consent to Continuation Out" menu when historical
=> Hide "Consent to Continuation Out" menu when historical

package-lock.json, package.json, src/components/EntityInfo/EntityHeader.vue, src/store/FilingHistoryList/getters.ts, src/store/getters.ts, tests/unit/EntityHeader.spec.ts
*Issue #:* /bcgov/entity#16153
- Badge is shown when Consent to Continuation Out is valid
=> 16153 - Use ccoExpiryDate for Consent ledger badge

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/filings/ConsentContinuationOut.vue
*Issue #:* /bcgov/entity#16344
- Ensure that the filing object is not pending before showing the item details. If it is pending or it does not contain a `data` object, use the default template.
*Reproducing the issue manually in the code:*
1. Add the following code into the `getFilings` return filter in the file `filingHistoryListStore.ts`:
```
filing.status = FilingStatus.PENDING
delete filing.data
```
2. Make sure `isStatusPaid` in the file `FilingTemplate.vue` always returns `true`.
3. Expand the details on the web app.
=> 16344 Fix pending consent ledger item blurb

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/filings/LimitedRestoration.vue, src/components/EntityInfo.vue, src/components/EntityInfo/EntityDefinitions.vue, src/components/EntityInfo/EntityHeader.vue, src/components/EntityInfo/EntityMenu.vue, src/stores/rootStore.ts, tests/unit/EntityHeader.spec.ts, tests/unit/EntityMenu.spec.ts
*Issue #:* /bcgov/entity#16544
- Move badges to their own line
- Put `active until` beside entity type
- Align top & bottom texts for entity info bar
- Show `HISTORICAL` badge only when business is historical (confirmed with Yui)
- Update unit tests
*Before:*
*After:*
*Before:*
*After:*
=> 16544 Update badge layout

package-lock.json, package.json, src/components/common/DetailComment.vue, src/views/Correction.vue
*Issue #:* /bcgov/entity#16048
I set the padding of the `v-textarea` to match the padding of the content inside the src/components/common/Certify.vue component (included in the screenshots). In that component, the content is wrapped with a `v-row` with `class` attributes to add padding. I did the same for the `v-textarea`, however it also works if it is wrapped in a plain old `div` with the same `class` attributes. I went with the `v-row` for consistency, however I also get if it doesn't make the most sense semantically and would be open to using a `div` instead.
I'll get UX to have a look after reviews to see if they have any preferences on the padding amount.
*Screenshot of changes:*
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> 16048 Fix broken styling for detail component

package-lock.json, package.json, src/assets/styles/base.scss, src/components/Dashboard/AddressListSm.vue, src/components/Dashboard/CustodianListSm.vue, src/components/Dashboard/DirectorListSm.vue, src/components/Dashboard/FilingHistoryList/FilingTemplate.vue, src/components/Dashboard/FilingHistoryList/filings/AlterationFiling.vue, src/components/Dashboard/FilingHistoryList/filings/ChangeOfAddress.vue, src/components/Dashboard/FilingHistoryList/filings/DissolutionVoluntary.vue, src/components/Dashboard/FilingHistoryList/filings/IncorporationApplication.vue, src/components/Dashboard/FilingHistoryList/filings/StaffFiling.vue, src/components/Dashboard/FilingHistoryList/subtitles/FiledAndPaid.vue, src/components/Dashboard/FilingHistoryList/subtitles/FiledAndPendingPaid.vue, src/components/Dashboard/FilingHistoryList/subtitles/FutureEffectiveFiledAndPendingCoa.vue, src/components/Dashboard/FilingHistoryList/subtitles/FutureEffectivePaid.vue, src/components/Dashboard/FirmsAddressList.vue, src/components/Dashboard/ProprietorPartnersListSm.vue, src/components/common/Directors.vue, src/components/common/SummaryDirectors.vue, src/views/AnnualReport.vue, src/views/ConsentContinuationOut.vue, src/views/ContinuationOut.vue, src/views/Correction.vue, src/views/Dashboard.vue, src/views/StandaloneDirectorsFiling.vue, src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* /bcgov/entity#16356
- Made the section numbers regular font weight and #212529 color
- Made the business detail ledger subtitles #495957 color
- Made other filing subtitles #495957 color
There are a couple places where the old gray color (gray6, #868E96) was used for UI elements (action button in `Directors.vue` and vertical bars in `base.scss`). I have held off on updating the gray in these places and have limited the changes to text only. If required, I can expand the changes to these UI elements as well.
=> 16356 Update the light grey text to meet AA contrast

package-lock.json, package.json, src/views/ContinuationOut.vue
*Issue #:* /bcgov/entity#16552
- Certify component was broken after the eslint presets update. 
This PR fixes that.
=> Hotfix continuation out certify component after eslint update

package-lock.json, package.json, src/assets/styles/theme.scss, src/components/EntityInfo.vue, src/components/EntityInfo/EntityHeader.vue
*Issue #:* /bcgov/entity#16253
- Janis' comment: https://github.com/bcgov/entity/issues/16253#issuecomment-1601800127
- New style:
- Style with a Pseudo 5th line that is going to be added later on:
**Note**: Janis asked for 30px of top and bottom spacing. However, since we use Vuetify Grid system, 30 is not a multiple of 4. So, I went with 28px 😄
CC: @janisrogers 
=> Fixed Ledger in response to Janis' comments

package-lock.json, package.json, src/interfaces/business-interfaces.ts, src/interfaces/dissolution-interfaces.ts, src/mixins/filing-mixin.ts, src/stores/businessStore.ts
*Issue #:* /bcgov/entity#17216
Add start date while building dissolution filing. This is a cleaner solution and start date can be saved to and fetched from `draftFiling` when filing a Dissolution in Create UI
=> 17216 - add start date while building dissolution filing

package-lock.json, package.json, src/components/Dashboard/TodoList.vue
*Issue #:* /bcgov/entity#17347
Missed check for resume button.
=> 17347 - Add in isCoop check for resume button.

src/components/AgmLocationChange/AgmYear.vue, src/views/AgmLocationChg.vue, tests/unit/AgmLocation.spec.ts, tests/unit/AgmLocationChg.spec.ts, tests/unit/AgmYear.spec.ts, tests/unit/EntityMenu.spec.ts
- Created unit tests for AGM Location
- Created unit tests for AGM year
- Fixed EntityMenu test from part 1 ticket
- Misc. fixes
**Note: I'm kind of blocked right on since I can't file the filing yet. I can't proceed on this before https://github.com/bcgov/business-schemas/pull/146 (schema) and https://github.com/bcgov/lear/pull/2258 (filer) are merged.**
=> AGM Location Change Third PR

package-lock.json, package.json, src/components/Dashboard/TodoList.vue, src/interfaces/api-filing-interface.ts, src/views/AgmLocationChg.vue, tests/unit/AgmLocation.spec.ts, tests/unit/EntityMenu.spec.ts
- Removed the option to cancel payment in case AGM Location change payment was unsuccessful
- Misc. fixes
~Note: The work for this ticket is mostly done. However, I won't merge until filer and schema are merged and verifying that everything looks good. I believe things should be fine in the filings history list.~ _Can merge now since I can file and it looks good._
=> AGM Location Change 4th and final PR

package-lock.json, package.json, src/views/AgmExtension.vue, src/views/AgmLocationChg.vue, src/views/ConsentContinuationOut.vue
- Certify block is now not editable for non-staff users (AGM filings)
=> Make Certify block non-editable if non-staff user (AGM Filings)

package-lock.json, package.json, src/components/AgmExtension/AboutTheBusiness.vue, tests/unit/AboutTheBusiness.spec.ts
*Issue #:* /bcgov/entity#18272
- Added unit tests for AboutTheBusiness component
=> 18272 Add unit test for AboutTheBusiness component

package-lock.json, package.json
*Issue #:* bcgov/entity#18513
- app version = 7.0.7
- imported latest ExpandableHelp component (to fix jerky transition)
=> 18513 Fixed jerky expandable help transition

package-lock.json, package.json, src/services/legal-services.ts, tests/unit/App.spec.ts, tests/unit/legal-services.spec.ts
*Issue #:* /bcgov/entity#17159
=> 17159 Update fetchNameRequest

package-lock.json, package.json, src/services/enum-utilities.ts, src/services/legal-services.ts
*Issue #:* bcgov/entity#18469
- app version = 7.0.11
- added missing cases for AGM filings
- added special case to convert "Agm" to "AGM"
- fixed a lint warning
=> 18469 Capitalize AGM in output titles

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/FilingHistoryList/filings/AgmExtension.vue, src/components/Dashboard/FilingHistoryList/filings/ContinuationOut.vue, src/components/Dashboard/FilingHistoryList/filings/index.ts, src/components/Dashboard/TodoList.vue, src/components/EntityInfo/EntityMenu.vue, src/components/common/ForeignJurisdiction.vue, src/interfaces/api-filing-interface.ts, src/services/enum-utilities.ts, src/views/AgmExtension.vue, tests/unit/AgmExtension.spec.ts, tests/unit/FilingHistoryList1.spec.ts
*Issue #:* bcgov/entity#18274
- app version = 7.0.12
- added AGM Extension as a filing in Filing History List
- added AGM Extension as cancellable Todo Item
- added AGM Extension filing component
- fixed wrong enum in Entity Menu
- added AGM Extension and AGM Location Change to Enum Utilities
- fixed misc type warnings
- added agmExtension fields to ApiFilingIF
- updated AGM Extension filing JSON per schema
- fixed unit test
- added FHL unit tests
*Screenshot:*
(Ignore the incorrect letter title above. It's because I was mocking the data.)
=> 18274 Updated To Do List and Recent Filing History

package-lock.json, package.json, src/App.vue, src/components/Dashboard/FilingHistoryList/filings/AmalgamationFiling.vue, src/components/Dashboard/TodoList.vue, src/components/EntityInfo.vue, src/components/EntityInfo/EntityMenu.vue, src/enums/routes.ts, src/interfaces/api-filing-interface.ts, src/interfaces/api-task-interface.ts, src/mixins/allowable-actions-mixin.ts, src/mixins/enum-mixin.ts, src/routes.ts, src/services/enum-utilities.ts, src/services/legal-services.ts, src/views/AmalgamationSelection.vue, tests/unit/AmalgamationFiling.spec.ts, tests/unit/App.spec.ts, tests/unit/EntityHeader.spec.ts, tests/unit/FilingHistoryList2.spec.ts, tests/unit/TodoList1.spec.ts, tests/unit/allowable-actions-mixin.spec.ts, tests/unit/filings.json
*Issues #:* bcgov/entity#18805 and bcgov/entity#18979
- Implemented the amalgamate button with it's rules and allowable actions
- Changed from amalgamation to amalgamationApplication + all accompanying changes
- Implemented the Amalgamation Selection Panel
UXPin: https://preview.uxpin.com/7f4cfe5fe4b0ba15a83d518177efe82a08e99167#/pages/160396524/simulate/sitemap
=> 18805+18979 Amalgamate Button + Moved to amalgamationApplication + Selection Panel

package-lock.json, package.json, src/components/Dashboard/TodoList.vue, src/interfaces/business-state-interfaces.ts, src/mixins/enum-mixin.ts, src/services/enum-utilities.ts, src/stores/businessStore.ts, src/stores/filingHistoryListStore.ts, src/stores/rootStore.ts, src/views/AgmExtension.vue, src/views/AgmLocationChg.vue, src/views/AnnualReport.vue, src/views/ConsentContinuationOut.vue, src/views/ContinuationOut.vue, src/views/Correction.vue, src/views/StandaloneDirectorsFiling.vue, src/views/StandaloneOfficeAddressFiling.vue, tests/unit/App.spec.ts
*Issue #:* bcgov/entity#19005
- app version = 7.0.30
- updated some code comments
- added AmalgamatedInto interface object
- added enum mixin and utility functions
- added some business store getters
- refactored getReasonText() and added case for amalgamation
- cast some parameters to pre-empt code errors
- added/updated unit tests
**Note:** This cannot be tested "for real" until a business is made historical by an amalgamation. I tested locally using mocked data as per the RFC / ticket. I also wrote some unit tests that verify all cases, so you can check there for the expected output.
=> 19005 Implemented historical - amalgamation reason text

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/interfaces/api-filing-interface.ts, src/stores/filingHistoryListStore.ts, tests/unit/EntityHeader.spec.ts, tests/unit/FilingHistoryList1.spec.ts, tests/unit/LegalObligation.spec.ts, tests/unit/filings.json
*Issue #:* /bcgov/entity#16967
=> 16967 Admin Freeze should not show on ledger

package-lock.json, package.json, src/components/Dashboard/Alerts/Amalgamation.vue, src/components/Dashboard/FilingHistoryList/LimitedRestorationExtensionFiling.vue, src/components/common/Certify.vue, src/components/common/DateTooltip.vue, src/interfaces/business-state-interfaces.ts, src/stores/businessStore.ts, src/views/Dashboard.vue, tests/unit/Amalgamation.spec.ts, tests/unit/Dashboard.spec.ts, tests/unit/DateTooltip.spec.ts, tests/unit/MissingInformation.spec.ts
*Issue #:* bcgov/entity#19291
- app version = 7.0.34
- moved some "unknown" from script to template
- added amalgamation alert component
- added optional data object to business warnings interface
- added getter for future effective amalgamation warning
- added alert to dashboard
- fixed some route type errors
- added test suite
**As the Legal API change for this has not yet been implemented, see ticket for local screenshots.**
=> 19291 Implemented "future effective amalgamation" alert

package-lock.json, package.json, src/components/EntityInfo/EntityMenu.vue, src/utils/feature-flags.ts, tests/unit/EntityMenu.spec.ts
- Don't display the amalgamate button if the FF doesn't support that entity type
=> Added amalgamation FF check

package-lock.json, package.json, src/components/dialogs/AddStaffNotationDialog.vue, src/components/dialogs/ConfirmDissolutionDialog.vue, src/components/dialogs/TechnicalErrorDialog.vue, src/components/dialogs/index.ts, src/enums/amalgamationEnums.ts, src/enums/index.ts, src/services/legal-services.ts, src/views/AmalgamationSelection.vue, tests/unit/AmalgamationSelection.spec.ts, tests/unit/TechnicalErrorDialog.spec.ts
*Issue #:* bcgov/entity#19209
- app version = 7.0.36
- fixed some getLegalType types
- added generic Technical Error Dialog (per Yui)
- added amalgamation enums
- refactored Legal Service function for better result and error handling
- added dialog to Amalgamation Selection component
- refactored Amalgamation Selection for error handling and to pre-populate TING business
- added test suite for new dialog
=> 19209 Pre-populate TING business + error handling

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/FilingHistoryList/FilingTemplate.vue
*Issue #:* bcgov/entity#19204
- app version = 7.0.37
- removed min-height (which simulated padding when it's a single line)
- added top margin (whitespace whether it's a single or wrapped line)
- added top padding to body for all filings
=> 19204 Fixed whitespace between sub-title and body

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/HeaderActions.vue, src/views/AmalgamationSelection.vue
*Issue #:* bcgov/entity#19823
- app version = 7.0.45
- removed numbered option for non-short-form (ie, regular) amalgamation
=> 19823 Revert pre-set numbered option for regular amalgamation

package-lock.json, package.json, src/components/Dashboard/TodoList.vue, src/components/common/ContactInfo.vue, src/components/dialogs/AffiliationErrorDialog.vue, src/components/dialogs/GenericErrorDialog.vue, src/components/dialogs/index.ts, src/stores/businessStore.ts, src/views/ConsentContinuationOut.vue, tests/unit/ConsentContinuationOut.spec.ts, tests/unit/GenericErrorDialog.spec.ts
*Issue #:* bcgov/entity#16756
- app version = 7.0.48
- bolded contact info labels (per design)
- renamed GenericErrorDialog -> AffiliationErrorDialog
- created GenericErrorDialog (same as Create UI)
- added new dialog, properties and logic to ConsentContinuationOut view
- make Court Order / POA section render for staff only
- added test suite for new dialog
=> 16756 Added special Court Order / POA handling in Consent for Continuation Out filing

package-lock.json, package.json, src/views/AmalgamationSelection.vue, src/views/ConsentContinuationOut.vue, src/views/ContinuationOut.vue
*Issue #:* bcgov/entity#20072
- app version = 7.0.49
- deleted Court Order Dialog from Consent Continuation Out view
*Also:*
- added fallback (to empty string) for business email and phone in draft amalgamation
- added fallback (to empty string) for business email in consent continuation out
- added fallback (to empty string) for business email in continuation out
=> 20072 Deleted Court Order dialog + added fallbacks for null business email/phone

package-lock.json, package.json, src/components/Dashboard/StaffNotation.vue, tests/unit/StaffNotation.spec.ts
*Issue #:* bcgov/entity#20162
- app version = 7.1.0
- show limited restoration staff actions according to allowable actions
=> 20162 Fixed logic for showing (vs disabling) limited restoration staff actions

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/filings/AgmExtension.vue, src/components/Dashboard/FilingHistoryList/filings/ConsentContinuationOut.vue, src/components/Dashboard/FilingHistoryList/filings/ContinuationOut.vue, src/components/common/ForeignJurisdiction.vue, src/interfaces/api-filing-interface.ts, src/views/AgmExtension.vue, src/views/AgmLocationChg.vue, src/views/AmalgamationOut.vue, src/views/AnnualReport.vue, src/views/ConsentAmalgamationOut.vue, src/views/ConsentContinuationOut.vue, src/views/ContinuationOut.vue, src/views/Correction.vue, src/views/StandaloneDirectorsFiling.vue, src/views/StandaloneOfficeAddressFiling.vue, tests/unit/ConsentAmalgamationOut.spec.ts, tests/unit/ConsentContinuationOut.spec.ts
*Issue #:* bcgov/entity#16847
- app version = ~7.1.4~ 7.1.6
- removed ledger detail ~for non-staff user~ for all users
- updated validation logic
- updated saveFiling()
*Also:*
- removed windows event handler  when local filings views are destroyed
*Also:*
- fixed some filing body margins
- fixed ApiFilingIF.continuationOut object
*Also:*
- fixed some calls that didn't need parameters
- fixed some typings
- removed order details display from CCO ledger item
- removed ledger detail section from CCO and CAO sub-components + all supporting code
=> 16847 Removed ledger detail in consent continue out / consent amalgamation out filings

package-lock.json, package.json, src/components/Dashboard/TodoList.vue, src/components/dialogs/AddStaffNotationDialog.vue, tests/unit/AddStaffNotationDialog.spec.ts, tests/unit/StaffNotation.spec.ts
*Issue #:* bcgov/entity#19202
- app version = 7.1.7
- removed unneeded code from TodoLlist.vue
- added paragraph
- hide notation form
- don't call ref methods if ref doesn't exist
- don't save `details`
=> 19202 Removed details from Admin Freeze/Unfreeze filings

package-lock.json, package.json, src/enums/index.ts, src/enums/nameType.ts, src/interfaces/business-state-interfaces.ts
*Issue #:* /bcgov/entity#20148
- Using the shared nameType enum now
=> 20148 updated to use the shared nameType enum

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/filings/DefaultFiling.vue, src/components/Dashboard/TodoList.vue, src/components/EntityInfo/EntityMenu.vue, src/interfaces/todo-item-interface.ts, src/mixins/allowable-actions-mixin.ts, tests/unit/AddStaffNotationDialog.spec.ts, tests/unit/EntityMenu.spec.ts, tests/unit/StaffNotation.spec.ts, tests/unit/TodoList1.spec.ts, tests/unit/allowable-actions-mixin.spec.ts
*Issue #:* bcgov/entity#16481
- app version = 7.1.9
- disabled AR checkbox when filing is not allowed
- added template block for "show delete only"
- implemented "show delete only" for dissolution
- implemented "show delete only" for alteration
- implemented "show delete only" for special resolution
- allowed resuming draft restoration even when NIGS
- added getters for Change Business Info button and Voluntary Dissolution list item
- added special case to enable button/item even if not allowed
- updated (simplified) logic for changing business info or showing dialog
- updated logic for confirming Voluntary Dissolution or showing dialog
- added missing subtype checks when computing whether Dissolutions are allowed
- added missing Admin Dissolution feature flag …
=> 16481 Fixes to allowed actions/dialogs/NIGS

package-lock.json, package.json, src/components/common/DetailComment.vue, src/views/ContinuationOut.vue, tests/unit/ContinuationOut.spec.ts
*Issue #:* /bcgov/entity#20534
Updated the details field for continue out so it's required for Staff filings but not for regular users. 
Set the default value to null
=> 20534-remove-details-field-for-users

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/subtitles/FiledAndPendingPaid.vue, src/components/Dashboard/FilingHistoryList/subtitles/FutureEffectivePaid.vue, tests/unit/FilingHistoryList1.spec.ts
*Issue #:* /bcgov/entity#21122
hide 'Hide Details' button for some filings
=> 21122 - hide 'Hide Details' button

package-lock.json, package.json, src/stores/businessStore.ts
*Issue #:* /bcgov/entity#21439
When the registration is draft, the code was checking for the name from alternate names but that doesn't exist at that point. When that is the case, we need to use the legal name as before. So, I simply added that check.
Before:
After:
=> 21439 - Fixed Unknown Name when registration is in draft

package-lock.json, package.json, src/views/Correction.vue, tests/unit/Correction.spec.ts
*Issue #:* bcgov/entity#21650
- app version = 7.2.11
- fixed invalid date for AGM year
=> 21650 Fixed invalid date for AGM year

package-lock.json, package.json, src/stores/businessStore.ts
*Issue #:* /bcgov/entity#21439
In my last PR, i missed the case when the firm is filed but still not completed. Basically what I had before `isDraftRegistration` was not enough.
When the SP or GP is filed and pending, it's not draft anymore but at the same time it's not completed. So, the alternate names array is not found.
Before:
After:
=> 21439 - Fixed unknown name when firm is filed and pending

package-lock.json, package.json, src/App.vue, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/FilingHistoryList/HeaderActions.vue, src/components/Dashboard/TodoList.vue, src/mixins/enum-mixin.ts, src/services/enum-utilities.ts, src/stores/rootStore.ts, tests/unit/HeaderActions.spec.ts, tests/unit/TodoList1.spec.ts, tests/unit/enum-utilities.spec.ts
*Issue #:* bcgov/entity#21846
- app version = 7.3.6
- renamed isTypeAmalgamation() -> isTypeAmalgamationApplication()
- updated doResumeFiling() to remove local correction routing
- refactored disableCorrection() to clearly show what happens for all filing types
- added some store getters
=> 21846 Updated list of filings enabled/disabled for corrections

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/HeaderActions.vue, src/components/Dashboard/TodoList.vue
*Issue #:* bcgov/entity#21928
- app version = 7.3.7
- enabled resume for all correction filing types
- enabled correction for all correction filing types (that are not disabled)
=> 21928 Allow corrections for missing types

package-lock.json, package.json, src/App.vue
*Issue #:* bcgov/entity#22084
- app version = 7.3.9
- clear existing tasks/filings before fetching new data
- added missing await in retry method
=> 22084 Clear data before reload

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList/HeaderActions.vue, src/utils/feature-flags.ts
*Issue #:* bcgov/entity#22446
- app version = 7.3.18
- allowed Annual Report corrections for specified legal types only (per FF)
- added new FF with default value
=> 22446 Allow AR corrections (depending on FF)

package-lock.json, package.json, src/components/Dashboard/FilingHistoryList.vue, src/components/Dashboard/FilingHistoryList/filings/ContinuationIn.vue, src/components/Dashboard/TodoList.vue, tests/unit/ContinuationIn.spec.ts
*Issue #:* bcgov/entity#21824
- app version = 7.3.19
- added vue-auto-resize package (for textareas)
- awaited async function in FilingHistoryList.vue
- replaced paragraph with textarea in TodoList.vue
- replaced paragraph with textarea in ContinuationIn.vue
=> 21824 Used textareas for latest review comments to preserve formatting

package-lock.json, package.json, src/components/Dashboard/TodoList.vue
*Issue #:* /bcgov/entity#23967 and /bcgov/entity#23636
- Fixed bug where spinner would show along with action button for in process filings.
_Before_
_After_
=> 23967 Make spinner pre-empt action button for in-process filings

package-lock.json, package.json, src/components/Dashboard/TodoList.vue
*Issue #:* /bcgov/entity#23969
When clicking on either button, both 2 buttons will be disabled, and the clicked one will have a loading spinner.
- To clearly communicate with users of the system status: something is being processed
- To prevent users clicking on the same button multiple times
**Before**:
**After**:
**Before**:
**After**:
=> 23969 do not authorize button spinner disabled after clicking

package-lock.json, package.json, src/App.vue
- app version = 7.4.4
- removed white border below app alert
- removed "!" due to alert type
- fixed colors
=> Fixed alert banner styles

package-lock.json, package.json, src/App.vue
*Issue #:* bcgov/entity#24423
- app version = 7.4.5
- on start, redirect to new dashboard if FF is True
=> 24423 Added conditional dashboard redirect

package-lock.json, package.json, src/App.vue
*Issue #:* bcgov/entity#24423
- app version = 7.4.7
- don't redirect to new dashboard for local filings
=> 24423 Only redirect when route is Dashboard

package-lock.json, package.json, src/components/NoticeOfWithdrawal/RecordToBeWithdrawn.vue, src/views/NoticeOfWithdrawal.vue
*Issue #:* /bcgov/entity#24953
- remove POA section text
- add an icon in submit button
- change document delivery section label
- Other changes are pending, discussing with Jacqueline
Jacqueline's UX assurance notes are here:
https://www.figma.com/design/CLqwqGQYARaSrnzLwh6w8Q/Notice-of-Withdrawal?node-id=700-16551&p=f&focus-id=2462-239471&m=dev
=> Fix 24953 - Update NoW Per New Designs

package-lock.json, package.json, src/App.vue, src/views/AmalgamationOut.vue, src/views/ConsentAmalgamationOut.vue, src/views/ConsentContinuationOut.vue, src/views/ContinuationOut.vue, src/views/NoticeOfWithdrawal.vue, tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#25294
- Fixed the issue: can't submit NoW for Bootstrap Filings
Reason: Bootstrap filings don't have those 3 properties set up - founding date, legal name and Registered Office email.
- Now stores the 3 properties in a bootstrap item's data fields in Filing UI
- Still can't Save/ Save and Resume, probably a bug in Legal API
=> 25294 - Submit NoW for Bootstrap Filing

package-lock.json, package.json, src/views/NoticeOfWithdrawal.vue
*Issue #:* /bcgov/entity#25745
- A bug due to recent changes: code allowing re-submit when filinId>0 was removed
- Fixed now
- Happens when payment is invalid, correct it, and re-submit - reproduce:
First, enter some invalid BC online account information, the click Submit;
Show the Pay error message;
Switch to "No Pay", try to submit again, trigger the error.
=> 25745-Fix NoW Resbumit Bug

package-lock.json, package.json
*Issue #:* /bcgov/entity#25522
=> 25522 update_shared_components

package-lock.json, package.json, src/components/common/ForeignJurisdiction.vue, tests/unit/ForeignJurisdiction.spec.ts
*Issue #:* /bcgov/entity#26915
- Jurisdiction should list Canada and United States of America at the top
- Canada and US are at the top and repeated in the list alphabetically. (Applies to Continuation Out too)
- Jurisdiction dropdown should be a type ahead and should show the matching entries in an abbreviated list
- Dropdown for Jurisdiction should appear under the input box
=> 26915 - Update Amalgamate Out filing page

package-lock.json, package.json, src/views/ConsentAmalgamationOut.vue
*Issue #:* /bcgov/entity#26914
- Verify the Jurisdiction selection works as expected:
a. list Canada and United States of America at the top
b. repeat them in the list alphabetically
c. has a type ahead and should show the matching entries in an abbreviated list
(This was done in the previous ticket, updated the shared component)
- Updated Documents Delivery text and Unsaved Changes text
=> 26914 - Update Consent Amalgamation Out Filing Page

package-lock.json, package.json, src/views/CourtOrder.vue, tests/unit/CourtOrder.spec.ts
*Issue #:* /bcgov/entity#27097
- Add the Cancel Confirm Dialog
- Change the initial Payment option to None
- Disable the File button when page is invalid, instead of loading
- When page is loaded, show fee
- Add validate to Staff Payment Section
=> 27097 - Fix Cancel Button for Court Order Filing

package-lock.json, package.json, src/views/CourtOrder.vue, tests/unit/CourtOrder.spec.ts
*Issue #:* /bcgov/entity#27097
- Before: the logic in determing whether 1.Court Order section is valid is problematic
Its validity solely depends on the Court Order Number section
- After update: the  validity depends Court Order Number section + File upload + input Text
=> Fix 27097 - Fix the Invalid Section Logic
